### ISSUE TITLE
How to manually (and correctly) resolve offsets?

### ISSUE THREAD

**Issue by unematiii** [Blizzard/node-rdkafka#1041]
So I'm wondering what is the correct way to achieve:
a) I want `node-rdkafka` to periodically auto-commit offsets
b) I want to manually store offsets to commit (in-case message processing fails)

I'm using the following to set up stream: 

```typescript
const stream = KafkaConsumer.createReadStream(
  {
    'client.id': 'client_id',
    'metadata.broker.list': 'brokers',
    'enable.auto.commit': true, // Enable auto-commit
    'enable.auto.offset.store': false, // We want to manually resolve offsets
    'group.id': 'group-id',
    'offset_commit_cb': true, // For logging purposes
    'partition.assignment.strategy': 'roundrobin',
  },
  {
    'auto.offset.reset': 'latest',
  },
  {
    fetchSize: 100,
    topics: ['topic'],
  },
);
```

And I use this to resolve offsets (right after message has been successfully consumed):

```typescript
public resolveOffset(message: Message) {
  const hasAssignment = this.stream.consumer
    .assignments()
    .some((v) => v.topic === message.topic && v.partition === message.partition);

    if (hasAssignment) {
      this.stream.consumer.offsetsStore([
        {
          offset: message.offset + 1,
          partition: message.partition,
          topic: message.topic,
        },
      ]); 
    }
}
```

However, `consumer.offsetsStore()` method still occasionally throws `Local: Erroneous state` error....

**Comment by robinfehr** [comment]
I think it would be good if you also print the librdkafka logs (including broker) to further investigate this - we use it in the same way and didn't see any issues with this approach. 

can you also show us the librdkafka config you use?

such as
    "enable.auto.offset.store",
    "enable.auto.commit"
    "auto.commit.interval.ms",
    "auto.offset.reset"
    
etc.

**Comment by unematiii** [comment]
@robinfehr Thanks for your reply. In addition to whats already shown, I also have basic SASL parameters in config (protocol, mechanism, username & password).

It's worth mentioning, that this issue happens rarely, sometimes once per two weeks in one of our production applications (`node-rdkafka 2.16.1`). I can also see increased memory usage (twice the normal). Unfortunately I haven't enabled full logging for librdkafka, I'll do it now and post when I know more.

I do wonder though, if specifying larger fetch size than default is okay here?

**Comment by antoniopironti** [comment]
I'm having the same issue, which can be replicated quite consistently with a consumer rebalance.

Broker logs when the first consumer joins the group:
```
[2024-03-13 09:57:09,684] INFO [GroupCoordinator 1]: Dynamic member with unknown member id joins group example-consumer-5 in Empty state. Created a new member id rdkafka-4bbb8859-cf4e-4d2b-8f5f-f5b5d9167829 and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2024-03-13 09:57:09,687] INFO [GroupCoordinator 1]: Preparing to rebalance group example-consumer-5 in state PreparingRebalance with old generation 0 (__consumer_offsets-25) (reason: Adding new member rdkafka-4bbb8859-cf4e-4d2b-8f5f-f5b5d9167829 with group instance id None; client reason: not provided) (kafka.coordinator.group.GroupCoordinator)
[2024-03-13 09:57:09,689] INFO [GroupCoordinator 1]: Stabilized group example-consumer-5 generation 1 (__consumer_offsets-25) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2024-03-13 09:57:09,691] INFO [GroupCoordinator 1]: Assignment received from leader rdkafka-4bbb8859-cf4e-4d2b-8f5f-f5b5d9167829 for group example-consumer-5 for generation 1. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
```

Broker logs when the second consumer joins the group (and the first one errors)

```
[2024-03-13 09:57:16,766] INFO [GroupCoordinator 1]: Dynamic member with unknown member id joins group example-consumer-5 in Stable state. Created a new member id rdkafka-675cbb63-cf1d-499f-8a0e-08ca1502529f and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2024-03-13 09:57:16,768] INFO [GroupCoordinator 1]: Preparing to rebalance group example-consumer-5 in state PreparingRebalance with old generation 1 (__consumer_offsets-25) (reason: Adding new member rdkafka-675cbb63-cf1d-499f-8a0e-08ca1502529f with group instance id None; client reason: not provided) (kafka.coordinator.group.GroupCoordinator)
[2024-03-13 09:57:18,755] INFO [GroupCoordinator 1]: Stabilized group example-consumer-5 generation 2 (__consumer_offsets-25) with 2 members (kafka.coordinator.group.GroupCoordinator)
[2024-03-13 09:57:18,757] INFO [GroupCoordinator 1]: Assignment received from leader rdkafka-4bbb8859-cf4e-4d2b-8f5f-f5b5d9167829 for group example-consumer-5 for generation 2. The group has 2 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2024-03-13 09:58:12,788] INFO [GroupCoordinator 1]: Member rdkafka-675cbb63-cf1d-499f-8a0e-08ca1502529f in group example-consumer-5 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
```

Error stack
```
LibrdKafkaError: Local: Erroneous state
    at Function.createLibrdkafkaError [as create] (.../node_modules/node-rdkafka/lib/error.js:456:10)
    at Client._errorWrap (.../node_modules/node-rdkafka/lib/client.js:481:29)
    at KafkaConsumer.offsetsStore (.../node_modules/node-rdkafka/lib/kafka-consumer.js:627:15
LibrdKafkaError: Local: Erroneous state
    at Function.createLibrdkafkaError [as create] (.../node_modules/node-rdkafka/lib/error.js:456:10)
    at Client._errorWrap (.../node_modules/node-rdkafka/lib/client.js:481:29)
    at KafkaConsumer.offsetsStore (.../node_modules/node-rdkafka/lib/kafka-consumer.js:627:15
...
code: -172,
errno: -172,
origin: 'kafka'
```

Unrelated - @unematiii, out of curiosity, why are you checking the partition assignment before processing a message? `librdkafka` purges the internal message queue on rebalance, so you shouldn't get any messages from partitions that are not currently assigned to the consumer?

**Comment by unematiii** [comment]
@antoniopironti I don't remember anymore, might of done that just out of precaution.

**Comment by unematiii** [comment]
@antoniopironti Also, if you're going to use stream wrapper, you might run into memory-leak issue. I never understood what causes it, but decreasing `queued.min.messages` helped. I set that to `500`.
