### ISSUE TITLE
Broker transport failure on Connect

### ISSUE THREAD

**Issue by thanpolas** [Blizzard/node-rdkafka#122]
I started having some very worrying behaviors on the services we develop, which typically use our [kafka-avro](https://github.com/waldophotos/kafka-avro) library which depends on node-rdkafka: `Service --> kafka-avro --> node-rdkafka`. 

The services will hang on boot while connecting to the local kafka. The consumer's `connect()` method callback will report an error:

```
Error on service boot: { Error: Local: Broker transport failure
      at Function.createLibrdkafkaError [as create] (/Users/thanpolas/Projects/work/waldo/waldo-input-dropbox/node_modules/node-rdkafka/lib/error.js:254:10)
      at /Users/thanpolas/Projects/work/waldo/waldo-input-dropbox/node_modules/node-rdkafka/lib/client.js:201:30
      at /Users/thanpolas/Projects/work/waldo/waldo-input-dropbox/node_modules/node-rdkafka/lib/client.js:342:9
    message: 'Local: Broker transport failure',
    code: -195,
    errno: -195,
    origin: 'kafka' }
```

All services using our kafka-avro library have this problem when I try to start them on my local, with a local kafka container (landoop/fast-data-dev). When deployed on our dev platform they operate as expected, boot, connect, operate normally. 

So right now we are going through what environmental factor might cause this critical behavior. If this kind of error rings any bells please do help.

I'll update this issue as more information becomes available

**Comment by thanpolas** [comment]
One major find was that `landoop/fast-data-dev` installs kafka 10 ... I'll find a kafka 9 build and test against that.

**Comment by thanpolas** [comment]
I figured this one out, the problem was that i used a url to point to the local kafka brokers `http://localhost:9092`, removing the http part and using just `localhost:9092` solved my connectivity problems.
