### ISSUE TITLE
Not working in docker container

### ISSUE THREAD

**Issue by vbicer** [Blizzard/node-rdkafka#158]
It's working on local machine. I've created an docker image, but it seems not working. Any idea?

web_1    | Error: /usr/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: invalid ELF header
web_1    |     at Error (native)
web_1    |     at Object.Module._extensions..node (module.js:597:18)
web_1    |     at Module.load (module.js:487:32)
web_1    |     at tryModuleLoad (module.js:446:12)
web_1    |     at Function.Module._load (module.js:438:3)
web_1    |     at Module.require (module.js:497:17)
web_1    |     at require (internal/module.js:20:19)
web_1    |     at bindings (/usr/src/app/node_modules/bindings/bindings.js:76:44)
web_1    |     at Object.<anonymous> (/usr/src/app/node_modules/node-rdkafka/librdkafka.js:10:32)
web_1    |     at Module._compile (module.js:570:32)

**Comment by vbicer** [comment]
My bad. I  forgot to add node_modules to .dockerignore file
