### ISSUE TITLE
Cannot start on node 8.0.0, cannot find libsasl2.0 even though it is disabled

### ISSUE THREAD

**Issue by robingador** [Blizzard/node-rdkafka#186]
I am running my project in a Docker container with Node 8.0.0.
I am using npm 5.0 to build and run.
Tested on node-rdkafka 1.0.0 and 0.10.2

Before running 'npm install' I disable SASL support with 'ENV WITH_SASL 0' in my Dockerfile.
The build is completed successfully.

But then when I start the Docker container I get the following error:
 `
Starting templatenodejs_web_1
Attaching to templatenodejs_web_1
web_1  | npm info it worked if it ends with ok
web_1  | npm info using npm@5.0.0
web_1  | npm info using node@v8.0.0
web_1  | npm info lifecycle template_nodejs@0.0.7~prestart: template_nodejs@0.0.7
web_1  | npm info lifecycle template_nodejs@0.0.7~start: template_nodejs@0.0.7
web_1  | 
web_1  | > template_nodejs@0.0.7 start /usr/src/app
web_1  | > node ./bin/www.js
web_1  | 
web_1  | /usr/src/app/node_modules/bindings/bindings.js:83
web_1  |         throw e
web_1  |         ^
web_1  | 
web_1  | Error: libsasl2.so.3: cannot open shared object file: No such file or directory
web_1  |     at Object.Module._extensions..node (module.js:598:18)
web_1  |     at Module.load (module.js:503:32)
web_1  |     at tryModuleLoad (module.js:466:12)
web_1  |     at Function.Module._load (module.js:458:3)
web_1  |     at Module.require (module.js:513:17)
web_1  |     at require (internal/module.js:11:18)
web_1  |     at bindings (/usr/src/app/node_modules/bindings/bindings.js:76:44)
web_1  |     at Object.<anonymous> (/usr/src/app/node_modules/node-rdkafka/librdkafka.js:10:32)
web_1  |     at Module._compile (module.js:569:30)
web_1  |     at Object.Module._extensions..js (module.js:580:10)
`
In my mind libsasl2 should not be required since it was successfully built without it. Something not compatible with latest Node 8.0.0 and npm 5.0??

**Comment by webmakersteve** [comment]
This suggests that there may be something new in `librdkafka` that depends on sasl that is not in our blacklist of files not to use. I'll look into making sure a sasl-less build works appropriately today.

**Comment by analytik** [comment]
Just in case this helps anyone, our Dockerfile does this to get node-rdkafka@1.0.x installed under Debian:Jessie -

```
RUN apt-get update \
    && apt-get install -y libssl-dev liblz4-dev libsasl2-dev libpthread-stubs0-dev build-essential pkg-config \
    && npm install -y \
    && apt-get remove -y g++-4.9 libstdc++-4.9-dev binutils cpp \
        libssl-dev liblz4-dev libsasl2-dev libpthread-stubs0-dev build-essential pkg-config \
        cpp-4.9 gcc-4.9 libasan1 libatomic1 libc-dev-bin libc6-dev libcilkrts5 \
        libcloog-isl4 libgcc-4.9-dev libgomp1 libisl10 libitm1 liblsan0 libmpc3 \
        libmpfr4 libquadmath0 libtsan0 libubsan0 linux-libc-dev manpages manpages-dev make \
    && apt-get autoremove -y \
    && apt-get clean
```

**Comment by webmakersteve** [comment]
Can you try this again now that we've upgraded to an official release of librdkafka? Would be interested to see if this reproduces.

**Comment by webmakersteve** [comment]
Closing due to inactivity. Please re-open if you have any additional comments on the newest version of the library.
