### ISSUE TITLE
Setting security.protocol throws Error: Invalid value for configuration property

### ISSUE THREAD

**Issue by hjespers** [Blizzard/node-rdkafka#203]
I am trying to set security.protocol = SASL_SSL.
Running on MacOS 10.12.5
Installed openssl via brew and have it working with Kafkacat (also librdkafka based).
Not sure how to force the compiler within npm install to build with sasl and ssl support.
Tried setting LDFLAGS=-L/usr/local/opt/openssl/lib and CPPFLAGS=-I/usr/local/opt/openssl/include and re-run npm install but with same results.

lots of WARN message during install such as ...
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl_cyrus.o
../deps/librdkafka/src/rdkafka_sasl_cyrus.c:66:21: warning: 'sasl_client_step' is deprecated: first deprecated in macOS 10.11 [-Wdeprecated-declarations]
                r = sasl_client_step(state->conn,
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/sasl/sasl.h:993:17: note: 'sasl_client_step' has been
      explicitly marked deprecated here
LIBSASL_API int sasl_client_step(sasl_conn_t *conn,
                ^
../deps/librdkafka/src/rdkafka_sasl_cyrus.c:94:29: warning: 'sasl_errdetail' is deprecated: first deprecated in macOS 10.11 [-Wdeprecated-declarations]
                            sasl_errdetail(state->conn));
                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/sasl/sasl.h:770:25: note: 'sasl_errdetail' has been
      explicitly marked deprecated here
LIBSASL_API const char *sasl_errdetail(sasl_conn_t *conn) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0,__MAC_10_11,__IPHONE_NA,__IPHONE_NA);

Full error message thrown while running the app is as follows:

Error: Invalid value for configuration property "security.protocol"
    at Error (native)
    at Producer.Client (/Users/hans/git/teslams-rdkafka/node_modules/node-rdkafka/lib/client.js:54:18)
    at new Producer (/Users/hans/git/teslams-rdkafka/node_modules/node-rdkafka/lib/producer.js:71:10)
    at Object.<anonymous> (/Users/hans/git/teslams-rdkafka/rdkstreaming.js:100:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by hjespers** [comment]
For my node install I was missing the step to ```Export CPPFLAGS=-I/usr/local/opt/openssl/include and LDFLAGS=-L/usr/local/opt/openssl/lib``` before I did  `npm install node-rdkafka`

These params are for macOS and are set to point to different directories from those used on Linux

Without them pointing to the right locations librdkafka can't compile with SSL and SASL support.

**Comment by hjespers** [comment]
For my node install I was missing the step to ```Export CPPFLAGS=-I/usr/local/opt/openssl/include and LDFLAGS=-L/usr/local/opt/openssl/lib``` before I did  `npm install node-rdkafka`

These params are for macOS and are set to point to different directories from those used on Linux

Without them pointing to the right locations librdkafka can't compile with SSL and SASL support.

**Comment by hjespers** [comment]
BTW the warnings about SASL being deprecated still appear but are just warnings because everything still works fine.
