### ISSUE TITLE
TLS error in run time

### ISSUE THREAD

**Issue by mjafarpour** [Blizzard/node-rdkafka#228]
Hi,
I want to use the lib but get this error in run time

`Error: /home/workspace/node_modules/node-rdkafka/build/Release/node-librdkafka.node: cannot allocate memory in static TLS block`

Node v4.2.6
Kafka 0.11
Ubuntu 16.04

**Comment by webmakersteve** [comment]
Can you give any additional context? Is this part of a stack trace?

**Comment by v3rse** [comment]
In my case, this after I run `WITH_SASL=0 npm install`
NB: `ldconfig -p | grep libsasl` returns the ff [Ubuntu 16.04 (i386)]:

```
libsasl2.so.2 (libc6) => /usr/lib/i386-linux-gnu/libsasl2.so.2
```
Find my stack trace below for the error during run time:

```
/home/user/work/project/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: /home/user/work/project/node_modules/node-rdkafka/build/Release/node-librdkafka.node: cannot allocate memory in static TLS block
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/home/user/work/project/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/user/work/project/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/work/project/node_modules/node-rdkafka/lib/client.js:14:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

**Comment by mjafarpour** [comment]
Hi,
This is full stack trace ....

`/home/mostafa/workspace/trading-system-event-base/node_modules/bindings/bindings.js:88
        throw e
        ^
Error: /home/mostafa/workspace/trading-system-event-base/node_modules/node-rdkafka/build/Release/node-librdkafka.node: cannot allocate memory in static TLS block
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/home/mostafa/workspace/trading-system-event-base/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/mostafa/workspace/trading-system-event-base/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (module.js:570:32)
`

**Comment by mjafarpour** [comment]
After install when run `make test` , the test failed with same error.

**Comment by webmakersteve** [comment]
Do you have openssl installed? and what configuration are you providing node-rdkafka?

**Comment by mjafarpour** [comment]
1.Yes, the 1.0.2 version of openssl installed.
2.it's not any specific configuration and in require command i get this error.

**Comment by webmakersteve** [comment]
https://stackoverflow.com/questions/45640934/error-while-loading-shared-libraries-cannot-allocate-memory-in-static-tls-block

I'm not sure if this is related, but did you compile node from source?

**Comment by mjafarpour** [comment]
Can you give me some advise for compile the source code?

**Comment by mjafarpour** [comment]
After clone the repository in my local directory, then i use `sudo npm install` to start the build process.
after include module get this Error:

/home/workspace/node_modules/node-rdkafka/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/workspace/node_modules/node-rdkafka/build/node-librdkafka.node
 → /home/workspace/node_modules/node-rdkafka/build/Debug/node-librdkafka.node
 → /home/workspace/node_modules/node-rdkafka/build/Release/node-librdkafka.node
 → /home/workspace/node_modules/node-rdkafka/out/Debug/node-librdkafka.node
 → /home/workspace/node_modules/node-rdkafka/Debug/node-librdkafka.node
 → /home/workspace/node_modules/node-rdkafka/out/Release/node-librdkafka.node
 → /home/workspace/node_modules/node-rdkafka/Release/node-librdkafka.node
 → /home/workspace/node_modules/node-rdkafka/build/default/node-librdkafka.node
 → /home/workspace/node_modules/node-rdkafka/compiled/6.11.3/linux/ia32/node-librdkafka.node
    at bindings (/home/workspace/node_modules/node-rdkafka/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/home/workspace/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/workspace/node_modules/node-rdkafka/lib/client.js:14:13)

**Comment by mjafarpour** [comment]
I use `nvm` to install my node and test with the versions 4.8.4, 6.11.3 and 8.5.0 but the Error is exist.

**Comment by mjafarpour** [comment]
I can solved it. These steps are required :

1.Change Ubuntu package server 
2. Reinstall all dependency package from new server 
3. Reinstall the Nodejs and Node-rdkafka.

**Comment by webmakersteve** [comment]
Yeah... I was afraid it was something to do with Node :(

Glad you got it figured out. Going to close the issue. Thanks for writing your solution in the issue!
