### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by fega** [Blizzard/node-rdkafka#266]
hello, I'm getting this

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-mq0x3HCAGGmQyZXviOVe5TRsw37Ijy3D43jCqt/9WVf+onx2dUgW3PosnqCbScAFhRO9DGs8nxoMzU0iiosMqQ== integrity checksum failed when using sha512: wanted sha512-mq0x3HCAGGmQyZXviOVe5TRsw37Ijy3D43jCqt/9WVf+onx2dUgW3PosnqCbScAFhRO9DGs8nxoMzU0iiosMqQ== but got sha1-EyfXCZULVY8gTlNSWH/QKQ+Njkg=. (68904 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
../deps/librdkafka/src/rdkafka_sasl_scram.c:45:2: error: #error "WITH_SSL (OpenSSL) is required for SASL SCRAM"
 #error "WITH_SSL (OpenSSL) is required for SASL SCRAM"
  ^~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:61:15: error: unknown type name ‘EVP_MD’
         const EVP_MD *evp;  /* Hash function pointer */
               ^~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c: In function ‘rd_base64_encode’:
../deps/librdkafka/src/rdkafka_sasl_scram.c:146:9: error: unknown type name ‘BIO’
         BIO *buf, *b64f;
         ^~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:147:9: error: unknown type name ‘BUF_MEM’
         BUF_MEM *ptr;
         ^~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:150:16: warning: implicit declaration of function ‘BIO_new’ [-Wimplicit-function-declaration]
         b64f = BIO_new(BIO_f_base64());
                ^~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:150:24: warning: implicit declaration of function ‘BIO_f_base64’ [-Wimplicit-function-declaration]
         b64f = BIO_new(BIO_f_base64());
                        ^~~~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:150:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         b64f = BIO_new(BIO_f_base64());
              ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:151:23: warning: implicit declaration of function ‘BIO_s_mem’ [-Wimplicit-function-declaration]
         buf = BIO_new(BIO_s_mem());
                       ^~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:151:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         buf = BIO_new(BIO_s_mem());
             ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:152:15: warning: implicit declaration of function ‘BIO_push’ [-Wimplicit-function-declaration]
         buf = BIO_push(b64f, buf);
               ^~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:152:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         buf = BIO_push(b64f, buf);
             ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:154:9: warning: implicit declaration of function ‘BIO_set_flags’ [-Wimplicit-function-declaration]
         BIO_set_flags(buf, BIO_FLAGS_BASE64_NO_NL);
         ^~~~~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:154:28: error: ‘BIO_FLAGS_BASE64_NO_NL’ undeclared (first use in this function)
         BIO_set_flags(buf, BIO_FLAGS_BASE64_NO_NL);
                            ^~~~~~~~~~~~~~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:154:28: note: each undeclared identifier is reported only once for each function it appears in
../deps/librdkafka/src/rdkafka_sasl_scram.c:155:9: warning: implicit declaration of function ‘BIO_set_close’ [-Wimplicit-function-declaration]
         BIO_set_close(buf, BIO_CLOSE);
         ^~~~~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:155:28: error: ‘BIO_CLOSE’ undeclared (first use in this function)
         BIO_set_close(buf, BIO_CLOSE);
                            ^~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:156:9: warning: implicit declaration of function ‘BIO_write’ [-Wimplicit-function-declaration]
         BIO_write(buf, in->ptr, (int)in->size);
         ^~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:157:9: warning: implicit declaration of function ‘BIO_flush’ [-Wimplicit-function-declaration]
         BIO_flush(buf);
         ^~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:159:9: warning: implicit declaration of function ‘BIO_get_mem_ptr’ [-Wimplicit-function-declaration]
         BIO_get_mem_ptr(buf, &ptr);
         ^~~~~~~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:160:25: error: request for member ‘length’ in something not a structure or union
         out = malloc(ptr->length + 1);
                         ^~
../deps/librdkafka/src/rdkafka_sasl_scram.c:161:24: error: request for member ‘data’ in something not a structure or union
         memcpy(out, ptr->data, ptr->length);
                        ^~
../deps/librdkafka/src/rdkafka_sasl_scram.c:161:35: error: request for member ‘length’ in something not a structure or union
         memcpy(out, ptr->data, ptr->length);
                                   ^~
../deps/librdkafka/src/rdkafka_sasl_scram.c:162:16: error: request for member ‘length’ in something not a structure or union
         out[ptr->length] = '\0';
                ^~
../deps/librdkafka/src/rdkafka_sasl_scram.c:164:9: warning: implicit declaration of function ‘BIO_free_all’ [-Wimplicit-function-declaration]
         BIO_free_all(buf);
         ^~~~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c: In function ‘rd_base64_decode’:
../deps/librdkafka/src/rdkafka_sasl_scram.c:176:9: error: unknown type name ‘BIO’
         BIO *b64, *bmem;
         ^~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:184:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         b64 = BIO_new(BIO_f_base64());
             ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:185:28: error: ‘BIO_FLAGS_BASE64_NO_NL’ undeclared (first use in this function)
         BIO_set_flags(b64, BIO_FLAGS_BASE64_NO_NL);
                            ^~~~~~~~~~~~~~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:187:16: warning: implicit declaration of function ‘BIO_new_mem_buf’ [-Wimplicit-function-declaration]
         bmem = BIO_new_mem_buf(in->ptr, (int)in->size);
                ^~~~~~~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:187:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         bmem = BIO_new_mem_buf(in->ptr, (int)in->size);
              ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:188:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         bmem = BIO_push(b64, bmem);
              ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:190:21: warning: implicit declaration of function ‘BIO_read’ [-Wimplicit-function-declaration]
         out->size = BIO_read(bmem, out->ptr, (int)asize+1);
                     ^~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c: In function ‘rd_kafka_sasl_scram_H’:
../deps/librdkafka/src/rdkafka_sasl_scram.c:218:51: error: ‘struct <anonymous>’ has no member named ‘scram_H’
         rktrans->rktrans_rkb->rkb_rk->rk_conf.sasl.scram_H(
                                                   ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:222:63: error: ‘struct <anonymous>’ has no member named ‘scram_H_size’
         out->size = rktrans->rktrans_rkb->rkb_rk->rk_conf.sasl.scram_H_size;
                                                               ^
../deps/librdkafka/src/rdkafka_sasl_scram.c: In function ‘rd_kafka_sasl_scram_HMAC’:
../deps/librdkafka/src/rdkafka_sasl_scram.c:236:15: error: unknown type name ‘EVP_MD’
         const EVP_MD *evp =
               ^~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:237:59: error: ‘struct <anonymous>’ has no member named ‘scram_evp’
                 rktrans->rktrans_rkb->rkb_rk->rk_conf.sasl.scram_evp;
                                                           ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:243:14: warning: implicit declaration of function ‘HMAC’ [-Wimplicit-function-declaration]
         if (!HMAC(evp,
              ^~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c: In function ‘rd_kafka_sasl_scram_Hi’:
../deps/librdkafka/src/rdkafka_sasl_scram.c:271:15: error: unknown type name ‘EVP_MD’
         const EVP_MD *evp =
               ^~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:272:59: error: ‘struct <anonymous>’ has no member named ‘scram_evp’
                 rktrans->rktrans_rkb->rkb_rk->rk_conf.sasl.scram_evp;
                                                           ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:274:31: error: ‘EVP_MAX_MD_SIZE’ undeclared (first use in this function)
         unsigned char tempres[EVP_MAX_MD_SIZE];
                               ^~~~~~~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:300:31: warning: unused variable ‘tempdest’ [-Wunused-variable]
                 unsigned char tempdest[EVP_MAX_MD_SIZE];
                               ^~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:274:23: warning: unused variable ‘tempres’ [-Wunused-variable]
         unsigned char tempres[EVP_MAX_MD_SIZE];
                       ^~~~~~~
In file included from /usr/include/stdlib.h:453:0,
                 from ../deps/librdkafka/src/rd.h:44,
                 from ../deps/librdkafka/src/rdkafka_int.h:44,
                 from ../deps/librdkafka/src/rdkafka_sasl_scram.c:33:
../deps/librdkafka/src/rdkafka_sasl_scram.c: In function ‘rd_kafka_sasl_scram_build_client_final_message’:
../deps/librdkafka/src/rdkafka_sasl_scram.c:408:36: error: ‘EVP_MAX_MD_SIZE’ undeclared (first use in this function)
                 { .ptr = rd_alloca(EVP_MAX_MD_SIZE) };
                                    ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:408:26: note: in expansion of macro ‘rd_alloca’
                 { .ptr = rd_alloca(EVP_MAX_MD_SIZE) };
                          ^~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c: In function ‘rd_kafka_sasl_scram_conf_validate’:
../deps/librdkafka/src/rdkafka_sasl_scram.c:870:33: error: ‘struct <anonymous>’ has no member named ‘scram_evp’
                 rk->rk_conf.sasl.scram_evp = EVP_sha1();
                                 ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:870:46: warning: implicit declaration of function ‘EVP_sha1’ [-Wimplicit-function-declaration]
                 rk->rk_conf.sasl.scram_evp = EVP_sha1();
                                              ^~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:871:33: error: ‘struct <anonymous>’ has no member named ‘scram_H’
                 rk->rk_conf.sasl.scram_H = SHA1;
                                 ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:871:44: error: ‘SHA1’ undeclared (first use in this function)
                 rk->rk_conf.sasl.scram_H = SHA1;
                                            ^~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:872:33: error: ‘struct <anonymous>’ has no member named ‘scram_H_size’
                 rk->rk_conf.sasl.scram_H_size = SHA_DIGEST_LENGTH;
                                 ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:872:49: error: ‘SHA_DIGEST_LENGTH’ undeclared (first use in this function)
                 rk->rk_conf.sasl.scram_H_size = SHA_DIGEST_LENGTH;
                                                 ^~~~~~~~~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:874:33: error: ‘struct <anonymous>’ has no member named ‘scram_evp’
                 rk->rk_conf.sasl.scram_evp = EVP_sha256();
                                 ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:874:46: warning: implicit declaration of function ‘EVP_sha256’ [-Wimplicit-function-declaration]
                 rk->rk_conf.sasl.scram_evp = EVP_sha256();
                                              ^~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:875:33: error: ‘struct <anonymous>’ has no member named ‘scram_H’
                 rk->rk_conf.sasl.scram_H = SHA256;
                                 ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:875:44: error: ‘SHA256’ undeclared (first use in this function)
                 rk->rk_conf.sasl.scram_H = SHA256;
                                            ^~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:876:33: error: ‘struct <anonymous>’ has no member named ‘scram_H_size’
                 rk->rk_conf.sasl.scram_H_size = SHA256_DIGEST_LENGTH;
                                 ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:876:49: error: ‘SHA256_DIGEST_LENGTH’ undeclared (first use in this function)
                 rk->rk_conf.sasl.scram_H_size = SHA256_DIGEST_LENGTH;
                                                 ^~~~~~~~~~~~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:878:33: error: ‘struct <anonymous>’ has no member named ‘scram_evp’
                 rk->rk_conf.sasl.scram_evp = EVP_sha512();
                                 ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:878:46: warning: implicit declaration of function ‘EVP_sha512’ [-Wimplicit-function-declaration]
                 rk->rk_conf.sasl.scram_evp = EVP_sha512();
                                              ^~~~~~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:879:33: error: ‘struct <anonymous>’ has no member named ‘scram_H’
                 rk->rk_conf.sasl.scram_H = SHA512;
                                 ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:879:44: error: ‘SHA512’ undeclared (first use in this function)
                 rk->rk_conf.sasl.scram_H = SHA512;
                                            ^~~~~~
../deps/librdkafka/src/rdkafka_sasl_scram.c:880:33: error: ‘struct <anonymous>’ has no member named ‘scram_H_size’
                 rk->rk_conf.sasl.scram_H_size = SHA512_DIGEST_LENGTH;
                                 ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:880:49: error: ‘SHA512_DIGEST_LENGTH’ undeclared (first use in this function)
                 rk->rk_conf.sasl.scram_H_size = SHA512_DIGEST_LENGTH;

**Comment by webmakersteve** [comment]
This looks like it may be a SASL problem? I can't really tell.

**Comment by fega** [comment]
yeah, I work and install node-rdkafka almost every day
Platform: ubuntu/linux 64x
the problem comes with the latest node-rdkafka version, the previous version is working okay

**Comment by fega** [comment]
the finish part of the snipped: 

```
../deps/librdkafka/src/rdkafka_sasl_scram.c:880:49: error: ‘SHA512_DIGEST_LENGTH’ undeclared (first use in this function)
                 rk->rk_conf.sasl.scram_H_size = SHA512_DIGEST_LENGTH;
                                                 ^~~~~~~~~~~~~~~~~~~~
deps/librdkafka.target.mk:171: fallo en las instrucciones para el objetivo 'Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl_scram.o'
make: *** [Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl_scram.o] Error 1
make: se sale del directorio '/home/fabian/Documentos/kickfit/mongauss/node_modules/node-rdkafka/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/fabian/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.0-59-generic
gyp ERR! command "/home/fabian/.nvm/versions/node/v8.5.0/bin/node" "/home/fabian/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fabian/Documentos/kickfit/mongauss/node_modules/node-rdkafka
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN mongauss@0.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fabian/.npm/_logs/2017-10-18T18_40_42_848Z-debug.log
```

**Comment by fega** [comment]
ouch, I closed this without notice it

**Comment by webmakersteve** [comment]
Can you try 2.1.1?

**Comment by Guatom** [comment]
These two solved everything for me in Ubuntu 16 x64:
`sudo apt-get install libssl-dev`
`sudo apt-get install libsasl2-dev`
Best of luck.

**Comment by webmakersteve** [comment]
Closing this issue because of inactivity.
