### ISSUE TITLE
Installation failed in Centos 7

### ISSUE THREAD

**Issue by Kevin-Lee** [Blizzard/node-rdkafka#275]
Installation failed in Centos 7

* OS: CentOS 7
* node-rdkafka version: 2.1.1
* node --version: v6.11.3
* npm --version: 3.10.10

The server has cyrus-sasl-devel and openssl-devel.

Since [node-rdkafka 2.0.0 couldn't connect Kafka with Kerberos and SSL](https://github.com/Blizzard/node-rdkafka/issues/274), I tried to install node-rdkafka 2.1.1 and got another problem.

After `npm --verbose install`, I got the following error messages.

```
npm info lifecycle node-rdkafka@2.1.1~install: node-rdkafka@2.1.1

> node-rdkafka@2.1.1 install /opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/node-rdkafka
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.11.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /root/.pyenv/shims/python2
gyp verb check python version `/root/.pyenv/shims/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.13\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.11.3
gyp verb command install [ '6.11.3' ]
gyp verb install input version string "6.11.3"
gyp verb install installing version: 6.11.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.11.3
gyp verb build dir attempting to create "build" dir: /opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/node-rdkafka/build
gyp verb build dir "build" dir needed to be created? /opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/node-rdkafka/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/node-rdkafka/build/config.gypi
gyp verb config.gypi checking for gypi file: /opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/node-rdkafka/config.gypi
gyp verb common.gypi checking for gypi file: /opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/node-rdkafka/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /root/.pyenv/shims/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/node-rdkafka/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.11.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.11.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules.bundled/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/node-rdkafka',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Please run configure before using this script
gyp: Call to 'node ../util/librdkafka-config-checker.js ENABLE_SSL' returned exit status 1 while in /opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/node-rdkafka/deps/librdkafka.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.49-moby
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/node-rdkafka
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm verb lifecycle node-rdkafka@2.1.1~install: unsafe-perm in lifecycle false
npm verb lifecycle node-rdkafka@2.1.1~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/node-rdkafka/node_modules/.bin:/opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/.bin:/root/.pyenv/shims:/root/.pyenv/bin:/root/.pyenv/shims:/root/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle node-rdkafka@2.1.1~install: CWD: /opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/node-rdkafka
npm info lifecycle node-rdkafka@2.1.1~install: Failed to exec install script
npm verb unlock done using /root/.npm/_locks/staging-d1590c61f7440bde.lock for /opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin/node_modules/.staging
contextual@0.1.0 /opt/kibana-4.6.4-linux-x86_64/installedPlugins/my-plugin
```

**Comment by matthax** [comment]
The install failed because it can't find `librdkafka` and the config/makefiles. Try running `git clone https://github.com/Blizzard/node-rdkafka.git node-rdkafka-fork --recursive` to ensure that `librdkafka` is downloaded as a dependency. Then you should be able to install.

**Comment by Kevin-Lee** [comment]
@matthax Oh?! I thought that was included in `node-rdkafka`. Anyway, I had `librdkafka` 0.11.1 when I installed `node-rdkafka`.
First I installed it by getting the source from https://github.com/edenhill/librdkafka then built it as instructed.
Yet I got that error so installed this RPM file from https://centos.pkgs.org/7/remi-x86_64/librdkafka-0.11.1-1.el7.remi.x86_64.rpm.html.
All the same result.

**Comment by matthax** [comment]
It's linked as a submodule in the actual repo, you've got to tell GitHub to clone it. Here's the process I use right now:
```sh
git clone https://github.com/Blizzard/node-rdkafka.git node-rdkafka --recursive
cd node-rdkafka
node-gyp rebuild
cd ..
cd some-other-project
npm install --save ../node-rdkafka
```

Try that, let me know if it works or not. Are you installing from `npm` when you encounter the error? Or are you trying to build this from source?

**Comment by Kevin-Lee** [comment]
@matthax Thanks Matt.

First I got,
```bash
# cd node-rdkafka
# node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.11.3 | linux | x64
gyp info spawn /root/.pyenv/shims/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/node-rdkafka/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.11.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.11.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/6.11.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/node-rdkafka',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
module.js:471
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at evalScript (bootstrap_node.js:353:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.49-moby
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/node-rdkafka
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```
so did `npm install` first.
```bash 
cd node-rdkafka
npm install
```
then `node-gyp rebuild` gave me
```bash
# node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.11.3 | linux | x64
gyp info spawn /root/.pyenv/shims/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/node-rdkafka/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.11.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.11.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/6.11.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/node-rdkafka',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Please run configure before using this script
gyp: Call to 'node ../util/librdkafka-config-checker.js ENABLE_SSL' returned exit status 1 while in /opt/node-rdkafka/deps/librdkafka.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.49-moby
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/node-rdkafka
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by petermetz** [comment]
@Kevin-Lee 

I'm not using CentOS, but had the exact same issue with node:alpine (which I had to ditch) as you do. Maybe it helps you as well.
This is how I got it working (thanks to @matthax for the tip on directly cloning the repo):

```
FROM node:8

###
### BEGIN node-rdkafka setup
###
WORKDIR /your-project-dir/node_modules/
RUN npm install -g node-gyp --production
RUN git clone https://github.com/Blizzard/node-rdkafka.git node-rdkafka --recursive
WORKDIR /your-project-dir/node_modules/node-rdkafka/
# Otherwise npm complains that it cannot work with git repositories inside node_modules, so delete the git repo ...
RUN rm -rf .git
RUN npm install nan
RUN ./configure
RUN node-gyp rebuild
###
### END node-rdkafka setup
###

WORKDIR  /your-project-dir/
COPY . .
RUN npm install --production

```

**Comment by webmakersteve** [comment]
You will need to run more than just node-gyp rebuild now since it uses a preinstall hook to hit the configure script that will only execute if you are using npm to wrap the node-gyp calls.

Glad to see you got it working - the `./configure` piece was the last step to making it work :) 

@Kevin-Lee  can you try that?

**Comment by Kevin-Lee** [comment]
@petermetz Great! Thanks a lot! I will try that.
@webmakersteve Yeah, I will and let you know the result. Thank you.
