### ISSUE TITLE
throw err Cannot find module 'node-rdkafka'

### ISSUE THREAD

**Issue by JonathanGladwin** [Blizzard/node-rdkafka#328]
Hello,

I have installed node-rdkafka using "npm install node-rdkafka" command on MacBook Pro. 
Then, I am trying to build the following node.js code in Eclipse, but observing the following throw error.

In Eclipse Node.JS application,

```
var Kafka = require('node-rdkafka');
var producer = new Kafka.Producer({
	  'metadata.broker.list': 'localhost:9092',
	  'dr_cb': true
	});

```

Build Error observed:

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'node-rdkafka'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pparasuraman/eclipse-workspace/NodeProject1/server.js:5:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Could someone please help me to solve this error, as I couldn't find a way to fix it?

**Comment by JonathanGladwin** [comment]
It has been solved by executing the following command in terminal,

cd /Users/pparasuraman/eclipse-workspace/NodeProject1
npm install --save node-rdkafka

https://stackoverflow.com/questions/47999276/throw-err-cannot-find-module-node-rdkafka
