### ISSUE TITLE
Getting error 'LZ4F_freeDecompressionContext: symbol not found' when running inside docker alpine

### ISSUE THREAD

**Issue by nadeem4n** [Blizzard/node-rdkafka#352]
Hi,

We are getting the following error when trying to include `node-rdkafka`. Here is the error stack trace (please see other details below).

```
/home/src/app/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_freeDecompressionContext: symbol not found
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at bindings (/home/src/app/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/src/app/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)

```

**Docker version:** 17.09
**System:** alpine-minirootfs-3.5.2-x86_64
**NodeJS version:** LTS 8.9.3
**node-rdkafka version:** 2.2.3

**Dockerfile:** 

```
FROM <our_base_alpine_using_above_alpine_pkg>

Run addgroup -g 1000 node \
    && adduser -u 1000 -G node -s /bin/sh -D -h /home node \
    && apk add --no-cache \
        libstdc++ \
        bash \
        python \
        g++ \
        make \
        openssl-dev \

    && apk add --no-cache --virtual .build-deps \
        binutils-gold \
        curl \
        gcc \
        gnupg \
        libgcc \
        linux-headers \
        glib-dev \

        && curl -SLO "https://nodejs.org/dist/v8.9.3/node-v8.9.3.tar.gz" \
        && tar -xf "node-v$8.9.3.tar.gz" \
        && cd "node-v$8.9.3" \
        && ./configure \
        && make -j$(getconf _NPROCESSORS_ONLN) \
        && make install \
        && cd .. \
        && rm -Rf "node-v$8.9.3" \
        && rm "node-v$8.9.3.tar.gz" \
       && chown -R node:node /usr 
```

And then we would use this base node image to create an actual app image where we would do `npm install` and start app which actually would do `require('node-rdkafka')` and use it.

Any thoughts?

**Comment by nadeem4n** [comment]
Hi @webmakersteve ,

I may have missed some details. This is not a compile time error, this is a **runtime error**.

Can you clarify this a little more?

```
As far as what I would recommend - maybe compiling and packing your application as a system package after building it on a node with full featured libraries would work? I think the libraries are statically compiled in (but I could be wrong).

Other than that you may need to put full featured versions of library dependencies in your alpine container to get it to work - or use a different flavor of linux.
```

Are there any specific instructions to compile it as a system package coz it may turn out to be the same issue even if we do that. Also about `full featured versions of library dependencies`, which specific libraries should we include / use?

**Comment by dima-guzi** [comment]
I think @webmakersteve meant recompiling the module with the problematic libraries installed.
Adding the following packages in Alpine then reinstalling node-rdkafka did the trick for me:
`lz4-dev lz4 lz4-libs py-lz4`
Not sure you need all of them, but it shouldn't cause problems anyways.

**Comment by nadeem4n** [comment]
It doesn't seem to be LZ4 only, if you run `ldd <your_app_dir>/node_modules/node-rdkafka/build/Release/node-librdkafka.node`, it shows a whole list of symbols it can't find. So it might be a good idea to statically compile all the dependencies (in case of alpine at least).

```
ldd /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node

------------------------
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v814ObjectTemplate21SetInternalFieldCountEi: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object17DefineOwnPropertyENS_5LocalINS_7ContextEEENS1_INS_4NameEEENS1_INS_5ValueEEENS_17PropertyAttributeE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object19GetOwnPropertyNamesEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN4node6Buffer6LengthEN2v85LocalINS1_6ObjectEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_freeDecompressionContext: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_compressUpdate: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value7IsArrayEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object3SetENS_5LocalINS_7ContextEEENS1_INS_5ValueEEES5_: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_async_send: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_compressEnd: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object3GetEj: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v816FunctionTemplate11GetFunctionEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_mutex_lock: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v87Isolate14ThrowExceptionENS_5LocalINS_5ValueEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_mutex_init: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object10GetIsolateEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value8ToStringENS_5LocalINS_7ContextEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_isError: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_getFrameInfo: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object3HasENS_5LocalINS_7ContextEEENS1_INS_5ValueEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value12IntegerValueENS_5LocalINS_7ContextEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_freeCompressionContext: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN4node6Buffer3NewEPN2v87IsolateEPcm: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v86String9WriteUtf8EPciPii: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v87Integer3NewEPNS_7IsolateEi: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value8IsRegExpEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_rwlock_wrunlock: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_rwlock_rdlock: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object3GetENS_5LocalINS_5ValueEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v814ObjectTemplate11NewInstanceENS_5LocalINS_7ContextEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object3GetENS_5LocalINS_7ContextEEENS1_INS_5ValueEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_default_loop: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v820EscapableHandleScopeC1EPNS_7IsolateE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v88Template3SetENS_5LocalINS_4NameEEENS1_INS_4DataEEENS_17PropertyAttributeE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object32SetAlignedPointerInInternalFieldEiPv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_decompress: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v811HandleScope12CreateHandleEPNS_8internal7IsolateEPNS1_6ObjectE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_compressBound: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v87Isolate17GetCurrentContextEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v89Signature3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_rwlock_destroy: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v816FunctionTemplate12SetClassNameENS_5LocalINS_6StringEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86String11NewFromUtf8EPNS_7IsolateEPKcNS_13NewStringTypeEi: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN4node6Buffer11HasInstanceEN2v85LocalINS1_5ValueEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value9IsBooleanEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_getErrorName: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value12BooleanValueENS_5LocalINS_7ContextEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_createDecompressionContext: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_compressBegin: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v811HandleScopeC1EPNS_7IsolateE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object20SlowGetInternalFieldEi: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN4node6AtExitEPFvPvES0_: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v88Function11NewInstanceENS_5LocalINS_7ContextEEEiPNS1_INS_5ValueEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object3SetENS_5LocalINS_5ValueEEES3_: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v87Context6GlobalEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v82V814CopyPersistentEPPNS_8internal6ObjectE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_async_init: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v82V817FromJustIsNothingEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Number3NewEPNS_7IsolateEd: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object38SlowGetAlignedPointerFromInternalFieldEi: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: node_module_register: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value10IsFunctionEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v88External5ValueEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v82V89ClearWeakEPPNS_8internal6ObjectE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value11Uint32ValueENS_5LocalINS_7ContextEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_rwlock_init: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v816FunctionTemplate11GetFunctionENS_5LocalINS_7ContextEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object16SetInternalFieldEiNS_5LocalINS_5ValueEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v811HandleScopeD2Ev: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v88External3NewEPNS_7IsolateEPv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object18InternalFieldCountEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value8IsObjectEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_close: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value10Int32ValueENS_5LocalINS_7ContextEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v82V812ToLocalEmptyEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v86String6LengthEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v814ObjectTemplate3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v82V813DisposeGlobalEPPNS_8internal6ObjectE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v85Array3NewEPNS_7IsolateEi: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v816FunctionTemplate16InstanceTemplateEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v811HandleScope12CreateHandleEPNS_8internal10HeapObjectEPNS1_6ObjectE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v811HandleScopeD1Ev: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Array6LengthEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v820EscapableHandleScope6EscapeEPPNS_8internal6ObjectE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_rwlock_wrlock: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPPNS1_6ObjectE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86String11NewFromUtf8EPNS_7IsolateEPKcNS0_13NewStringTypeEi: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object3NewEPNS_7IsolateE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value8ToObjectENS_5LocalINS_7ContextEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v86RegExp9GetSourceEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v89Exception5ErrorENS_5LocalINS_6StringEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v87Isolate10GetCurrentEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v816FunctionTemplate17PrototypeTemplateEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_mutex_unlock: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_queue_work: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN4node12MakeCallbackEPN2v87IsolateENS0_5LocalINS0_6ObjectEEENS3_INS0_8FunctionEEEiPNS3_INS0_5ValueEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_mutex_destroy: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v86Object3SetEjNS_5LocalINS_5ValueEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value7ToInt32ENS_5LocalINS_7ContextEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN4node6Buffer4DataEN2v85LocalINS1_6ObjectEEE: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: LZ4F_createCompressionContext: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZNK2v85Value8IsNumberEv: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: uv_rwlock_rdunlock: symbol not found
Error relocating /home/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: _ZN2v82V88MakeWeakEPPNS_8internal6ObjectEPvPFvRKNS_16WeakCallbackInfoIvEEENS_16WeakCallbackTypeE: symbol not found
```

**Comment by webmakersteve** [comment]
Alpine does not come with glibc, and instead uses an alternative library. This has caused many problems in the past, and I'm not convinced they are unsurmountable. I'm working on some changes to the node-rdkafka build process that will hopefully help the issue, but for now maybe this will help:

https://github.com/Blizzard/node-rdkafka/issues/111

**Comment by SkeLLLa** [comment]
@webmakersteve In my case this error appears event if I use alpine with glibc installed (e.g. see frolvlad/alpine-glibc on dockerhub).

So the problem is in configure stage.
Here's a log of configure phase without `lz4-dev` package installed:
```
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
...
Configuration summary:
...
  ENABLE_LZ4_EXT           y
```

It doesn't find lz4 and enables it for some reason. So obviously it will fail to find it in runtime.

**Comment by webmakersteve** [comment]
Has this been fixed with the newer builds? As specified, I was able to get it working in alpine as part of that reported issue.
