### ISSUE TITLE
Use master branch of librdkafka

### ISSUE THREAD

**Issue by krishanfrog** [Blizzard/node-rdkafka#366]
I am facing an issue with consumers during rebalancing. 

I see that the issue has been fixed on the master branch of librdkafka and I want to test and use the updated library. Is there a documented/safe way of updating the librdkafka library in the node module?

**Comment by krishanfrog** [comment]
I tried using the master code of librdkafka using the following steps

1. Updated the code in deps/librdkafka/
2. Ran the following commands in deps/librdkafka
```
./configure
  make
  sudo make install
```
3. Ran node-gyp configure and node-gyp build from node-rdkafka directory

When I start my process I get the below error

```
/server/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: dlopen(/server/node_modules/node-rdkafka/build/Release/node-librdkafka.node, 1): Symbol not found: _unittest_murmur2
  Referenced from: /server/node_modules/node-rdkafka/build/Release/node-librdkafka.node
  Expected in: flat namespace
 in /server/node_modules/node-rdkafka/build/Release/node-librdkafka.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/server/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/server/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

Anything else that I need to do to integrate?

**Comment by krishanfrog** [comment]
@webmakersteve any help here on how to proceed

**Comment by webmakersteve** [comment]
Make sure to export `BUILD_LIBRDKAFKA=0` when building so it uses the system librdkafka rather than the one packaged with the code. You can do that even without `cd`ing into the module directory just by making sure that is set before you run `npm install`

**Comment by krishanfrog** [comment]
Thanks
