### ISSUE TITLE
node-rdkafka 2.3.2 build fails due to unsatisfied rule?

### ISSUE THREAD

**Issue by IdanAdar** [Blizzard/node-rdkafka#409]
Error log: 
```
npm WARN lifecycle node-rdkafka@2.3.2~preinstall: cannot run in wd %s %s (wd=%s) node-rdkafka@2.3.2 node util/configure /var/jenkins/workspace/kafka-consumer_PR-15-LOKOYFOWG3PU23VFFKVWOLISIOFOPSY5SHBR6POKGLCNP7WLWYPQ/node_modules/.staging/node-rdkafka-3978422a
> node-rdkafka@2.3.2 install /var/jenkins/workspace/kafka-consumer_PR-15-LOKOYFOWG3PU23VFFKVWOLISIOFOPSY5SHBR6POKGLCNP7WLWYPQ/node_modules/node-rdkafka
> node-gyp rebuild

make: Entering directory `/var/jenkins/workspace/kafka-consumer_PR-15-LOKOYFOWG3PU23VFFKVWOLISIOFOPSY5SHBR6POKGLCNP7WLWYPQ/node_modules/node-rdkafka/build'
make: *** No rule to make target `/var/jenkins/workspace/kafka-consumer_PR-15-LOKOYFOWG3PU23VFFKVWOLISIOFOPSY5SHBR6POKGLCNP7WLWYPQ/node_modules/node-rdkafka/deps/librdkafka/config.h', needed by `_var_jenkins_workspace_kafka_consumer_PR_15_LOKOYFOWG3PU23VFFKVWOLISIOFOPSY5SHBR6POKGLCNP7WLWYPQ_node_modules_node_rdkafka_deps_librdkafka_gyp_librdkafka_target_build_dependencies.intermediate'.  Stop.
make: Leaving directory `/var/jenkins/workspace/kafka-consumer_PR-15-LOKOYFOWG3PU23VFFKVWOLISIOFOPSY5SHBR6POKGLCNP7WLWYPQ/node_modules/node-rdkafka/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-693.21.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/jenkins/workspace/kafka-consumer_PR-15-LOKOYFOWG3PU23VFFKVWOLISIOFOPSY5SHBR6POKGLCNP7WLWYPQ/node_modules/node-rdkafka
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
```

Notes:
- build passes with v2.0.0
- machine actually uses Node 8.11.1 (installed using nvm), not sure why it says 7.9.0... does the version matter here?

**Comment by IdanAdar** [comment]
Is there a difference between Mac and Linux in recent node-rdkafka releases?
in Mac the build passes. In Linux (CentOS) it fails.

**Comment by IdanAdar** [comment]
I think this has to do with the Node version node-gyp uses. It's unclear to me why is it taking Node from /usr/local/bin/node. I'm also not clear on how to use the `--target` flag for node-gyp when the build is starting via an automated job rather than manually.

**Comment by IdanAdar** [comment]
Looks like all it took was a restart of the build machine and a re-setting of the default node version. blat.

**Comment by webmakersteve** [comment]
Glad to see it worked out for you. Was on vacation, and just got back!
