### ISSUE TITLE
Build issue with 2.3.2 on Linux with Node 6

### ISSUE THREAD

**Issue by mimaison** [Blizzard/node-rdkafka#415]
We're having issues building 2.3.2 on Linux with Node 6:

```
SOLINK_MODULE(target) Release/obj.target/node-librdkafka.node
       g++: error: /tmp/app/node_modules/node-rdkafka/build/deps/librdkafka.so: No such file or directory
       g++: error: /tmp/app/node_modules/node-rdkafka/build/deps/librdkafka++.so: No such file or directory
       rm _tmp_app_node_modules_node_rdkafka_deps_librdkafka_gyp_librdkafka_target_build_dependencies.intermediate
       make: Leaving directory `/tmp/app/node_modules/node-rdkafka/build'
       gyp ERR! build error
       gyp ERR! stack     at ChildProcess.onExit (/tmp/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
       gyp ERR! stack     at emitTwo (events.js:106:13)
       gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
       gyp ERR! System Linux 4.4.0-109-generic
       gyp ERR! command "/tmp/app/vendor/node/bin/node" "/tmp/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/app/node_modules/node-rdkafka
       gyp ERR! node -v v6.12.3
       gyp ERR! node-gyp -v v3.4.0
       make: *** [Release/obj.target/node-librdkafka.node] Error 1
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! not ok
       npm ERR! Linux 4.4.0-109-generic
       npm ERR! argv "/tmp/app/vendor/node/bin/node" "/tmp/app/vendor/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/app/.npmrc"
       npm ERR! node v6.12.3
       npm ERR! npm  v3.10.10
       npm ERR! code ELIFECYCLE
       npm ERR! Exit status 1
       npm ERR! Failed at the node-rdkafka@2.3.2 install script 'node-gyp rebuild'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs node-rdkafka
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls node-rdkafka
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/app/npm-debug.log
-----> Build failed
```

We've tested master and it's working fine (We've not done a bisect to identify the exact commit).

As 2.3.2 is published to npm this is the version many people pick. So even if it's only been a few days since 2.3.2 what about cutting a 2.3.3 ?

**Comment by webmakersteve** [comment]
2.3.3 is cut. Sorry for the delay.

**Comment by mimaison** [comment]
Thanks @webmakersteve 2.3.3 works like a charm!
