### ISSUE TITLE
"Error: Local: Queue full" when dr_cb set to false

### ISSUE THREAD

**Issue by sanoel** [Blizzard/node-rdkafka#438]
Hi,
I'm running into this Queue full error even when `dr_cb: false`. Is this behavior expected? I've also tried  `dr_cb: true` with a 100 ms polling interval (commented out below). The code below comes from the Producer tutorial with only a couple changes to the Producer configuration. This was run in docker using wurstmeister/kafka docker image. Thanks for any help!

Here is the error:
```testkafka    | /code/testkafka/node_modules/node-rdkafka/lib/client.js:471
testkafka    |     throw e;
testkafka    |     ^
testkafka    | Error: Local: Queue full
testkafka    |     at Function.createLibrdkafkaError [as create] (/code/testkafka/node_modules/node-rdkafka/lib/error.js:260:10)
testkafka    |     at Producer.Client._errorWrap (/code/testkafka/node_modules/node-rdkafka/lib/client.js:470:29)
testkafka    |     at Producer.produce (/code/testkafka/node_modules/node-rdkafka/lib/producer.js:134:15)
testkafka    |     at Producer.<anonymous> (/code/testkafka/test.js:43:14)
testkafka    |     at emitTwo (events.js:130:20)
testkafka    |     at Producer.emit (events.js:213:7)
testkafka    |     at /code/testkafka/node_modules/node-rdkafka/lib/client.js:212:12
testkafka    |     at /code/testkafka/node_modules/node-rdkafka/lib/client.js:348:7
```

**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Ubuntu 16.04.3 LTS
 - Node Version [e.g. 8.2.1]: v9.11.1
 - NPM Version [e.g. 5.4.2]: 5.6.0
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]: 1.6.0

**Steps to Reproduce**
```var Kafka = require('node-rdkafka');                                             
                                                                                 
var producer = new Kafka.Producer({                                              
  'debug' : 'all',                                                               
  'metadata.broker.list': 'kafkatest',                                           
  'queue.buffering.max.messages': 10000,  // to hit the limit a bit more quickly                                       
  'dr_cb': false  //delivery report callback                                     
});                                                                              
                                                                                 
console.log(producer)                                                            
var topicName = 'test';                                                          
                                                                                 
//logging debug messages, if debug is enabled                                    
producer.on('event.log', function(log) {                                         
  console.log(log);                                                              
});                                                                              
                                                                                 
//logging all errors                                                             
producer.on('event.error', function(err) {                                       
  console.error('Error from producer');                                          
  console.error(err);                                                            
});                                                                              
                                                                                 
//counter to stop this sample after maxMessages are sent                         
var counter = 0;                                                                 
var maxMessages = 10000;                                                         
                                                                                 
producer.on('delivery-report', function(err, report) {                           
  console.log('delivery-report: ' + JSON.stringify(report));                     
  counter++;                                                                     
});                                                                              
                                                                                 
//Wait for the ready event before producing                                      
producer.on('ready', function(arg) {                                             
  console.log('producer ready.' + JSON.stringify(arg));                          
                                                                                 
  for (var i = 0; i < maxMessages; i++) {                                      
    var value = new Buffer('value-' +i);                                         
    var key = "key-"+i;                                                          
    // if partition is set to -1, librdkafka will use the default partitioner    
    var partition = -1;                                                          
    producer.produce(topicName, partition, value, key);                          
  }                                                                              
                                                                                 
  //need to keep polling for a while to ensure the delivery reports are received 
  /*    dr_cb set to false so do we need to                                                                          
  var pollLoop = setInterval(function() {                                        
      producer.poll();                                                           
      if (counter === maxMessages) {                                             
        clearInterval(pollLoop);                                                 
        producer.disconnect();                                                   
      }                                                                          
    }, 100);                                                                    
    */                                                                           
});                                                                              
console.log('ready listener started')                                            
                                                                                 
producer.on('disconnected', function(arg) {                                      
  console.log('producer disconnected. ' + JSON.stringify(arg));                  
});
```

**Comment by sanoel** [comment]
Closing as I realized I misunderstood the need to poll whether delivery reports are requested or not. I think I may have also been running into issues with producing messages at a rate faster than kafka was polling.

**Comment by webmakersteve** [comment]
Sorry I couldn't get to you in time! But glad you figured it out. To circumvent the problem you can produce with node-rdkafka in a setImmediate block to give the event loop some time to breathe, at the cost of buffering the function calls in memory.
