### ISSUE TITLE
How can I set dr_msg_cb in nodejs code?, below is the error I'm getting on startup

### ISSUE THREAD

**Issue by sureshzebpay** [Blizzard/node-rdkafka#445]
**Environment Information**
 - Ubuntu
 - Node Version : v8.11.3
 - NPM Version: 5.6.0

on trying to connect producer

```
Error: Property "dr_msg_cb" must be set through dedicated .._set_..() function
0|KNC-BTCO |     at KafkaConsumer.Client (/home/blockchain/Desktop/suresh.prajapati/projects/ordermatcher/node_modules/node-rdkafka/lib/client.js:54:18)
0|KNC-BTCO |     at new KafkaConsumer (/home/blockchain/Desktop/suresh.prajapati/projects/ordermatcher/node_modules/node-rdkafka/lib/kafka-consumer.js:117:10)
0|KNC-BTCO |     at Object.<anonymous> (/home/blockchain/Desktop/suresh.prajapati/projects/ordermatcher/consumer.js:12:18)
0|KNC-BTCO |     at Module._compile (module.js:652:30)
0|KNC-BTCO |     at Object.Module._extensions..js (module.js:663:10)
0|KNC-BTCO |     at Module.load (module.js:565:32)
0|KNC-BTCO |     at tryModuleLoad (module.js:505:12)
0|KNC-BTCO |     at Function.Module._load (module.js:497:3)
0|KNC-BTCO |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:83:21)
0|KNC-BTCO |     at Module._compile (module.js:652:30)
```

**node-rdkafka Configuration Settings**

How can I fix this?

**Comment by webmakersteve** [comment]
Can you send your constructor code for your Producer? Those are special config values that need to be set a specific way.

**Comment by sureshzebpay** [comment]
This is my config values
```
"consumerKafka" : {
            'group.id': 'orderbook',
            'metadata.broker.list': 'localhost:9092',
            'socket.keepalive.enable': true,
            'debug': 'generic,broker,security',
            'dr_msg_cb': true
        },
```

Here is my constructor code:

```
const Kafka = require('node-rdkafka');
const consumer = new Kafka.KafkaConsumer(kafkaConf);
```
