### ISSUE TITLE
Error running on node < NODE_MODULE_VERSION 64

### ISSUE THREAD

**Issue by alexayalabonilla** [Blizzard/node-rdkafka#446]
**Environment Information**
 - OS Mac
 - Node Version 8.11.1
 - NPM Version 5.6.0
 - C++ Toolchain g++
 - node-rdkafka version 2.3.4

**Steps to Reproduce**

Install and run using node v8.11.1

**Additional context**

/Users/abonilla/projects/SVN/APG_R2/apps/Fl_Bridge/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings .....node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/...../node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

**Works If I switch to node v10.5.0**

**Comment by alexayalabonilla** [comment]
I was a problem on my environment not sure what, was a coincidence that the error happened after I update the node-rdkafka version
