### ISSUE TITLE
Error: `make` failed with exit code: 2 while npm install

### ISSUE THREAD

**Issue by sp-suresh** [Blizzard/node-rdkafka#451]
npm install fails with node-rdfkakfka in ubuntu 16.04.

node ver - 10.6.0
npm ver - 6.1.0

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.13.0-45-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/local/ZEBPAY/suresh.prajapati/projects/tradesync/node_modules/int64-native
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! int64-native@0.4.0 install: `node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the int64-native@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Here is additional log in file - 
[err.log](https://github.com/Blizzard/node-rdkafka/files/2201417/err.log)

**Comment by webmakersteve** [comment]
`npm ERR! Failed at the int64-native@0.4.0 install script.`

That is a different package than this one, and node-rdkafka does not depend on it.

**Comment by rsryanstephen** [comment]
Hey I'm getting the same error except for 
"Failed at the node-rdkafka@2.4.1 install script."
I do not understand what the posted solution means?
