### ISSUE TITLE
Error occured when call consumer.disconnect

### ISSUE THREAD

**Issue by yulidai** [Blizzard/node-rdkafka#461]
Error occured when call consumer.disconnect
Sometimes is success, but sometimes failed. Error info is below:

2018-08-01 11:33:57,353 INFO 1298 Do disconnect from kafka, wait..
2018-08-01 11:33:57,354 ERROR 1298 Something bad happened:  Error: Local: Erroneous state
    at KafkaConsumer.assign (/Users/leedy/Develop/consumer/node_modules/_node-rdkafka@2.3.4@node-rdkafka/lib/kafka-consumer.js:243:16)
    at KafkaConsumer.rebalance_cb (/Users/leedy/Develop/consumer/app/kafka/consumer.js:26:14)
    at KafkaConsumer.conf.rebalance_cb (/Users/leedy/Develop/consumer/node_modules/_node-rdkafka@2.3.4@node-rdkafka/lib/kafka-consumer.js:82:20)
2018-08-01 11:33:57,355 ERROR 1298 nodejs.Error: Local: Erroneous state (uncaughtException throw 1 times on pid:1298)
    at KafkaConsumer.assign (/Users/leedy/Develop/consumer/node_modules/_node-rdkafka@2.3.4@node-rdkafka/lib/kafka-consumer.js:243:16)
    at KafkaConsumer.rebalance_cb (/Users/leedy/Develop/consumer/app/kafka/consumer.js:26:14)
    at KafkaConsumer.conf.rebalance_cb (/Users/leedy/Develop/consumer/node_modules/_node-rdkafka@2.3.4@node-rdkafka/lib/kafka-consumer.js:82:20)

pid: 1298
hostname: localhost

[Wed Aug 01 2018 11:33:57 GMT+0800 (CST)] [graceful:worker:1298:uncaughtException] throw error 1 times
Error: Local: Erroneous state
    at KafkaConsumer.assign (/Users/leedy/Develop/consumer/node_modules/_node-rdkafka@2.3.4@node-rdkafka/lib/kafka-consumer.js:243:16)
    at KafkaConsumer.rebalance_cb (/Users/leedy/Develop/consumer/app/kafka/consumer.js:26:14)
    at KafkaConsumer.conf.rebalance_cb (/Users/leedy/Develop/consumer/node_modules/_node-rdkafka@2.3.4@node-rdkafka/lib/kafka-consumer.js:82:20)
Error: Local: Erroneous state
    at KafkaConsumer.assign (/Users/leedy/Develop/consumer/node_modules/_node-rdkafka@2.3.4@node-rdkafka/lib/kafka-consumer.js:243:16)
    at KafkaConsumer.rebalance_cb (/Users/leedy/Develop/consumer/app/kafka/consumer.js:26:14)
    at KafkaConsumer.conf.rebalance_cb (/Users/leedy/Develop/consumer/node_modules/_node-rdkafka@2.3.4@node-rdkafka/lib/kafka-consumer.js:82:20)
[Wed Aug 01 2018 11:33:57 GMT+0800 (CST)] [graceful:worker:1298] will exit after 30000ms
[Wed Aug 01 2018 11:33:57 GMT+0800 (CST)] [graceful:worker:1298] close server#0, _connections: 0
[Wed Aug 01 2018 11:33:57 GMT+0800 (CST)] [graceful:worker:1298] close 1 servers!
[Wed Aug 01 2018 11:33:57 GMT+0800 (CST)] [graceful:worker:1298] worker disconnect!
[2018-08-01 11:33:57.357] [cfork:master:1296] worker:1298 disconnect (exitedAfterDisconnect: true, state: disconnected, isDead: false, worker.disableRefork: false)
[2018-08-01 11:33:57.358] [cfork:master:1296] don't fork new work (refork: false)
2018-08-01 11:33:57,358 INFO 1296 [master] app_worker#1:1298 disconnect, suicide: true, state: disconnected, current workers: ["1"]
[Wed Aug 01 2018 11:34:27 GMT+0800 (CST)] [graceful:worker:1298] kill timeout, exit now.
2018-08-01 11:34:27,362 ERROR 1298 [app_worker] exit with code:1
^C2018-08-01 11:34:37,201 INFO 1296 [master] receive signal SIGINT, closing
2018-08-01 11:34:37,204 INFO 1296 [master] wait 1000ms

**Comment by yulidai** [comment]
OS: Mac
Node Version: 8.11.3
NPM Version: 5.6.0
node-rdkafka version: 2.3.4

Any help is appreciated!

**Comment by yulidai** [comment]
The major question is: when error occurred, it will not call callback function and pass error to the first param(err), instead of that just throw the error.  

And it's not a async function, so i cannot catch and handle it.

when i use process.once('uncaughtException') to catch this error, the program still dead

**Comment by yulidai** [comment]
Sorry...it's my fault. The error was thrown in rebalance_cb.

The note of documents is:
"this can throw when you are disconnected. Take care and wrap it in a try catch if that matters to you"

Yes, when disconnected, sometimes it will happen.
When it happens i will catch it and do reconnect.
But the callback of comsumer.connect is called and error is "undefined", the "ready" event never be listend. How should i do to reconnect kafka?

reconnect in below:
```
if (err.code === Kafka.CODES.ERRORS.ERR__ASSIGN_PARTITIONS) {
  // Note: this can throw when you are disconnected. Take care and wrap it in
  // a try catch if that matters to you
  
  try {
    this.assign(assignment);
    consumer.connect();
  } catch(err) {
    console.log(err);
    consumer.connect();
  }
}
```

**Comment by yulidai** [comment]
And when it happens, disconnected event never be listend to

**Comment by yulidai** [comment]
Now i know, the status is still connecting, so "ready" will not emitted even though calling connect because the status never disconnect.

So i try to call disconnect after checking connect status, but the callback function of consumer.disconnect will never be called.

```
       if (err.code === Kafka.CODES.ERRORS.ERR__ASSIGN_PARTITIONS) {
        // Note: this can throw when you are disconnected. Take care and wrap it in
        // a try catch if that matters to you
        try {
          this.assign(assignment);
        } catch(err) {
          app.logger.error(`Assign failed, will reconnect because of: ${err}`);
          app.logger.info(`Is connected? Result: ${this.isConnected()}`);
          while(this.isConnected()) {
            await disconnectUntilSuccess(); //Wrapped by promise
          }
          //consumer.emit('disconnected');
        }
      }
```

**Comment by yulidai** [comment]
So another question is: if i remove the rebalance_cb function, then rebalancing will be managed internally by librdkafka. The disconnect will occur the same problem?

**Comment by yulidai** [comment]
```
module.exports = app => {

  const consumer = new Kafka.KafkaConsumer({
    // **** other config ****
    
    // disable auto commit
    //'enable.auto.commit': true,

    rebalance_cb: async function (err, assignment) {
      if (err.code === Kafka.CODES.ERRORS.ERR__ASSIGN_PARTITIONS) {
        try {
          this.assign(assignment);
        } catch(err) {
          app.logger.error(`Assign failed, may be need reconnect because of: ${err}`);

          //sometimes success, sometimes failed( here is the problem !!!!! )
          //if i remove rebalance_cb, it will always disconnect success internally by librdkafka?
          while(this.isConnected()) {
            await disconnectUntilSuccess(); //Wrapped by promise
          }
        }
      } else if (err.code == Kafka.CODES.ERRORS.ERR__REVOKE_PARTITIONS) {
        this.unassign();
      } else {
      // We had a real error
        app.logger.error(err);
      }
    },
  });

  //connect
  connectUntilSuccess();
  consumer.on('disconnected', () => {
    app.logger.info('Listend disconnected event, do reconnect.')
    connectUntilSuccess();
  })

  //处理数据
  let dataList = null;
  consumer.on('ready', async function() {
    while(true) {
      try {
        dataList = await getNewData();
      } catch(err) {
        app.logger.error(`Error occured when getting data from kafka: ${err}`);
        disconnectUntilSuccess();
        break;
      }

      //** process data, then commit

    }
  });

  function getNewData() {
    return new Promise(async (resolve, reject) => {
      // why need timeout? because:
      // 1. sometimes will never return data, and status is still connect
      // 2. if use "consume(); consumer.on('data', handler)", all will be ok but not fit our needs
      // 3. same problem in rust, so may be the problem is official's.
      let taskTimeoutWatcher = setTimeout( () => reject('timeout'), 20000 );
      
      consumer.consume(300, (err, dataList) => {
        //** handle err
        resolve(dataList);
      });
    })
  }

  return consumer;
};
```
