### ISSUE TITLE
error installing node-rdkafka package trying to run yarn install 

### ISSUE THREAD

**Issue by cyberbot143** [Blizzard/node-rdkafka#499]
**Environment Information**
 **- OS [e.g. Mac, Arch, Windows 10]: MacOS High Sierra : 10.13.6
 - Node Version [e.g. 8.2.1]: 8.11.3
 - NPM Version [e.g. 5.4.2]:5.60
 - node-rdkafka version [e.g. 2.3.3] : 2.4.1**

i'm using yarn 

Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.3 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/svurug964/Documents/graph-api-ecms-flow/node_modules/node-rdkafka/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/svurug964/.node-gyp/8.11.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/svurug964/.node-gyp/8.11.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/svurug964/.node-gyp/8.11.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/svurug964/Documents/graph-api-ecms-flow/node_modules/node-rdkafka',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, inscript_main
    return main(sys.argv[1:])
  File "/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, inmain
    return gyp_main(args)
  File "/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, ingyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 766, in Write
    extra_mac_bundle_resources, part_of_all)
  File "/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 872, in WriteActions
    env = self.GetSortedXcodeEnv()
  File "/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1851, in GetSortedXcodeEnv
    additional_settings)
  File "/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1584, in GetSortedXcodeEnv
    additional_settings)
  File "/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1495, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
  File "/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/svurug964/.nvm/versions/node/v8.11.3/bin/node" "/Users/svurug964/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/svurug964/Documents/graph-api-ecms-flow/node_modules/node-rdkafka
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2

**Comment by jtadmor** [comment]
Hi!

I fixed this by upgrading to `node-gyp v.3.6.3` by doing `npm explore npm -g -- npm install node-gyp@3.6.3`.

(See: https://github.com/nodejs/node-gyp/wiki/Updating-npm's-bundled-node-gyp)

**Comment by DarkMortal** [comment]
I'm facing this exact same issue
