### ISSUE TITLE
preinstalling librdkafka

### ISSUE THREAD

**Issue by aeternitatus** [Blizzard/node-rdkafka#551]
hi all,

I have couple of microservices using node-rdkafka, all containerized. Now I'd like to save build time and have a parent container with librdkafka preinstalled.

here is what I do in that parent container (I could not find 0.11.5 deb packages to install, so decided to build from sources):
```
RUN wget -qO- https://github.com/edenhill/librdkafka/archive/v${RDK_VERSION}.tar.gz | tar -xzf - -C /tmp \
    && cd /tmp/librdkafka-${RDK_VERSION} \
    && ./configure --prefix=$RDK_PREFIX \
    && make \
    && make install \
    && make clean \
    && ./configure --clean \
    && ls -l $RDK_PREFIX/lib \
    && rm -rf /tmp/librdkafka-${RDK_VERSION}

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RDK_PREFIX/lib
ENV ENV BUILD_LIBRDKAFKA=0
```

in $RDK_PREFIX/lib I see the following:
```
-rwxr-xr-x 1 root root  3041096 Jan  1 22:31 librdkafka++.a
lrwxrwxrwx 1 root root       17 Jan  1 22:31 librdkafka++.so -> librdkafka++.so.1
-rwxr-xr-x 1 root root  1163024 Jan  1 22:31 librdkafka++.so.1
-rwxr-xr-x 1 root root 13275808 Jan  1 22:31 librdkafka.a
lrwxrwxrwx 1 root root       15 Jan  1 22:31 librdkafka.so -> librdkafka.so.1
-rwxr-xr-x 1 root root  5592296 Jan  1 22:31 librdkafka.so.1
drwxr-xr-x 2 root root     4096 Jan  1 22:31 pkgconfig
```

now in each of the child container I have node-rdkafka dependencies in package.json, but I do not want librdkafka to be built each time I build an image for microservice(s).
But, whenever I run `npm install` there I have an error:
```
Step 39/43 : RUN NODE_TLS_REJECT_UNAUTHORIZED=0  &&  npm install --no-optional
 ---> Running in aeb01697a238

> node-rdkafka@2.4.1 install /app/node_modules/node-rdkafka
> node-gyp rebuild

make: Entering directory '/app/node_modules/node-rdkafka/build'
  CXX(target) Release/obj.target/node-librdkafka/src/binding.o
In file included from ../src/binding.cc:11:0:
/app/node_modules/node-rdkafka/src/binding.h:15:24: fatal error: rdkafkacpp.h: No such file or directory
 #include "rdkafkacpp.h"
                        ^
compilation terminated.
make: *** [Release/obj.target/node-librdkafka/src/binding.o] Error 1
node-librdkafka.target.mk:116: recipe for target 'Release/obj.target/node-librdkafka/src/binding.o' failed
make: Leaving directory '/app/node_modules/node-rdkafka/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/node-rdkafka
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN cds.delta-calculator@0.1.1 No description
npm WARN cds.delta-calculator@0.1.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-01T22_31_23_947Z-debug.log
```

what is missing? what am I doing wrong? 

node=10.13
npm=6.4.1
node-rdkafka=2.4.1
librdkafka=0.11.5
docker=18.09.0
base image=node:10.13

**Comment by aeternitatus** [comment]
ok, I guess I fixed it.. but looks like a workaround:
1. not passing --prefix (i.e. configuring with defaults)
2. therefore not changing LD_LIBRARY_PATH 
3. calling ldconfig

```
RUN wget -qO- https://github.com/edenhill/librdkafka/archive/v${RDK_VERSION}.tar.gz | tar -xzf - -C /tmp \
    && cd /tmp/librdkafka-${RDK_VERSION} \
    && ./configure \
    && make \
    && make install \
    && ldconfig \
    && make clean \
    && ./configure --clean \
    && rm -rf /tmp/librdkafka-${RDK_VERSION}
```

now it works, `npm install node-rdkafka@2.4.1` creates nodejs-c bindings only, without recompiling librdkafka each time..
