### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sgermain06** [Blizzard/node-rdkafka#552]
**Environment Information**
 - OS: Mac OS Mojave (10.14.2)
 - Node Version: v11.3.0
 - NPM Version: 6.5.0
 - C++ Toolchain: xcode 10 (llvm)
 - node-rdkafka version: 2.5.1

**Steps to Reproduce**
Simply type `npm i node-rdkafka`

**node-rdkafka Configuration Settings**

**Additional context**
> node-rdkafka@2.5.1 install /<redacted>/node_modules/node-rdkafka
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  ACTION deps_librdkafka_gyp_librdkafka_target_configure deps/librdkafka/config.h
checking for OS or distribution... ok (osx)
checking for C compiler from CC env... ok
checking for C++ compiler from CXX env... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for debug symbols compiler flag (-g...)... failed
checking for pkgconfig (by command)... ok
checking for install (by command)... failed
checking for PIC (by compile)... failed (disable)
checking for GNU-compatible linker options... failed
checking for OSX linker options... ok
checking for GNU linker-script ld flag... failed
checking for Solaris linker-script ld flag... failed (ignore)
checking for __atomic_32 (by compile)... failed
checking for __atomic_32_lib (by compile)... failed
checking for __sync_32 (by compile)... failed (disable)
checking for __atomic_64 (by compile)... failed
checking for __atomic_64_lib (by compile)... failed
checking for __sync_64 (by compile)... failed (disable)
checking for socket (by compile)... failed
checking for socket_nsl (by compile)... failed (fail)
parsing version '0x000b05ff'... ok (0.11.5)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... failed
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... failed (fail)
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... failed (disable)
checking for zlib (by pkg-config)... ok
checking for zlib (by compile)... ok (cached)
checking for libcrypto (by pkg-config)... failed
checking for libcrypto (by compile)... ok
checking for libm (by pkg-config)... failed
checking for libm (by compile)... failed (disable)
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for rapidjson (by compile)... failed (disable)
checking for libssl (by pkg-config)... ok
checking for libssl (by compile)... ok (cached)
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... failed (disable)
checking for libsasl (by pkg-config)... failed
checking for libsasl (by compile)... failed (disable)
checking for crc32chw (by compile)... failed (disable)
checking for regex (by compile)... failed (disable)
checking for strndup (by compile)... failed (disable)
checking for strerror_r (by compile)... failed (disable)
checking for pthread_setname_gnu (by compile)... failed (disable)
checking for nm (by env NM)... ok (cached)

###########################################################
###########################################################
###########################################################
 socket_nsl () 
    module: socket
    action: fail
    reason:
compile check failed:
CC: CC
flags: 
x86_64-apple-darwin13.4.0-clang -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/usr/local/opt/openssl/include -g -O2 -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpdH4ne9.c -o _mkltmpdH4ne9.c.o -lsocket -lnsl -L/usr/local/opt/openssl/lib -L/<redacted>/node_modules/node-rdkafka/build/deps :
ld: library not found for -lsocket
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
source: 
#include <sys/types.h>
#include <sys/socket.h>
#include <unistd.h>
void foo (void) {
   int s = socket(0, 0, 0);
   close(s);
}

 libpthread () 
    module: librdkafka
    action: fail
    reason:
compile check failed:
CC: CC
flags: -lpthread
x86_64-apple-darwin13.4.0-clang -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/usr/local/opt/openssl/include -g -O2 -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpjoakXR.c -o _mkltmpjoakXR.c.o  -L/usr/local/opt/openssl/lib -L/<redacted>/node_modules/node-rdkafka/build/deps -lpthread:
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libpthread.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libpthread.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
source: #include <pthread.h>

make: *** No rule to make target `../deps/librdkafka/config.h', needed by `11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/<redacted>/.nvm/versions/node/v11.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/<redacted>/.nvm/versions/node/v11.3.0/bin/node" "/<redacted>/.nvm/versions/node/v11.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /<redacted>/node_modules/node-rdkafka
gyp ERR! node -v v11.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /<redacted>/.npm/_logs/2019-01-02T15_38_27_713Z-debug.log

**Comment by sgermain06** [comment]
Turns out that the problem was with Anaconda. I removed the CC export from my `.bash_profile` and it compiled correctly.
