### ISSUE TITLE
Error: Invalid topic partition provided

### ISSUE THREAD

**Issue by Vijendra07Kulhade** [Blizzard/node-rdkafka#555]
Error on `consumer.commit(topicPartition)`
```consumer ready.{"name":"rdkafka#consumer-2"}
delivery-report: {"topic":"msg.local","partition":0,"offset":12,"key":null,"opaque":"0_69","timestamp":1546927409048,"size":36780}
/Users/xxxxx/WebstormProjects/consumerproducer/node_modules/node-rdkafka/lib/kafka-consumer.js:489
{ topic: 'msg.local', partition: '0', offset: 70 }
  this._errorWrap(this._client.commit(topicPartition), true);
                               ^

Error: Invalid topic partition provided
    at KafkaConsumer.commit (/Users/xxxx/WebstormProjects/consumerproducer/node_modules/node-rdkafka/lib/kafka-consumer.js:489:32)
    at Producer.<anonymous> (/Users/xxxx/WebstormProjects/consumerproducer/src/simple-data-mirror.js:57:14)
    at Producer.emit (events.js:182:13)
    at onDeliveryReport (/Users/xxxxx/WebstormProjects/consumerproducer/node_modules/node-rdkafka/lib/producer.js:93:12)
```
**Environment Information**
 - OS [Mac Os Mojave]: 
 - Node Version [10.7.0]:
 - NPM Version [6.5.0]:
 - C++ Toolchain []:
 - node-rdkafka version [2.5.1]:

**Steps to Reproduce**
Commit offset after getting the producer delivery report. 
I set the opaque to keep track of produced messages and commit those offset only.
**node-rdkafka Configuration Settings**
```
const Kafka = require('node-rdkafka');

const srcTopic = 'msg-local';
const consumer = new Kafka.KafkaConsumer({
    // 'debug': 'all',
    'bootstrap.servers': 'localhost:9092',
    'group.id': 'node-rdkafka-consumer-flow-example',
    'topic.metadata.refresh.interval.ms':20000,
    'api.version.request':false,
    'receive.message.max.bytes':210000000,
    'enable.auto.commit': false
},{
    'message.timeout.ms':300000,
    'auto.offset.reset':'earliest',
    'offset.store.sync.interval.ms':5000
});

const producer = new Kafka.Producer({
    // 'debug' : 'all',
    'client.id':'noderd-kafka',
    'bootstrap.servers': 'localhost:9092',
    'broker.version.fallback':'0.10.2.0',
    'heartbeat.interval.ms':3000,
    'compression.codec': 'none',
    'request.required.acks':1,
    'api.version.request':false,
    'retry.backoff.ms': 200,
    'message.send.max.retries': 10,
    'socket.keepalive.enable': true,
    'queue.buffering.max.messages': 100000,
    'queue.buffering.max.ms': 10000,
    'batch.num.messages': 10000,
    'dr_cb': true
},{
    'message.timeout.ms':300000,
    'produce.offset.report':true,
    'acks':1,
    'offset.store.sync.interval.ms':10
});
producer.on('ready',(arg)=>{
    consumer.on('data',function(m) {
        let value = Buffer.from(m.value.toString(),'utf-8');
        let key = m.key===null?null:m.key.toString();
        // console.log(value);
        producer.produce('msg.local',m.partition,value,key,Date.now(),m.partition+"_"+m.offset);
    });
});


producer.on('delivery-report', function(err, report) {
    console.log('delivery-report: ' + JSON.stringify(report));
    const topicPartition={
        'topic':'msg.local',
        'partition':report['opaque'].split("_")[0],'offset':++report['opaque'].split("_")[1]
    };
    console.log(topicPartition);
    consumer.commit(topicPartition);

});
consumer.on('ready', function(arg) {
    console.log('consumer ready.' + JSON.stringify(arg));

    consumer.subscribe([srcTopic]);
    //start consuming messages
    setInterval(function() {
        consumer.consume(1000);
    }, 1000);
});
//logging debug messages, if debug is enabled
consumer.on('event.log', function(log) {
    console.log(log);
});

//logging all errors
consumer.on('event.error', function(err) {
    console.error('Error from consumer',err);
});
consumer.connect();
//starting the producer
producer.connect();
producer.setPollInterval(100);
//logging debug messages, if debug is enabled
producer.on('event.log', function(log) {
    console.log("event.log", log);
});
```

**Additional context**

**Comment by klayhb** [comment]
Ran into this as well, happens when you pass a string for partition (even if it's a string representation of a number)

**Comment by iradul** [comment]
This is expected behavior.
How about converting it into a number by just adding `+` in front of it, for example:
```
    const topicPartition={
        'topic':'msg.local',
        'partition':+report['opaque'].split("_")[0],
        'offset':++report['opaque'].split("_")[1]
    };
```
