### ISSUE TITLE
Error when initializing Kafka Admin Client in Ubuntu 16.04

### ISSUE THREAD

**Issue by deepakc** [Blizzard/node-rdkafka#583]
**Environment Information**
 - OS 
_NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial_
 
 - Node Version : _v10.15.3_
 - NPM Version : _6.4.1_
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version : _2.5.1_

**Steps to Reproduce**

Run a simple admin client to create a topic from the example in the Readme section - https://github.com/Blizzard/node-rdkafka#admin-client,

```
const Kafka = require('node-rdkafka');
console.log(Kafka.librdkafkaVersion);

const client = Kafka.AdminClient.create({
    "client.id": "********",
    "metadata.broker.list": "********",
    "security.protocol": "SASL_SSL",
    "sasl.mechanisms": "SCRAM-SHA-256",
    "sasl.username": "******",
    "sasl.password": "********"    
  });
  
  client.createTopic({
    topic: "test-topic",
    num_partitions: 1,
    replication_factor: 1
  }, function(err) {
      console.log("Done");
      console.log(err);
    // Done!
  });
```

**node-rdkafka Configuration Settings**

**Additional context**

Here is the error,
```
0.11.5
/home/admin-test/node_modules/node-rdkafka/lib/error.js:273
    throw e;
    ^
Error: Local: Erroneous state
    at Function.createLibrdkafkaError [as create] (/home/admin-test/node_modules/node-rdkafka/lib/error.js:261:10)
    at Function.errorWrap [as wrap] (/home/admin-test/node_modules/node-rdkafka/lib/error.js:272:29)
    at AdminClient.connect (/home/admin-test/node_modules/node-rdkafka/lib/admin.js:93:19)
    at Object.createAdminClient [as create] (/home/admin-test/node_modules/node-rdkafka/lib/admin.js:32:31)
    at Object.<anonymous> (/home/admin-test/src/kafka-admin-test.js:4:34)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by tanuj32soni** [comment]
I am having a similar issue, Have you found any solution yet?
