### ISSUE TITLE
npm install --save node-rdkafka fails

### ISSUE THREAD

**Issue by mikolajprzybysz** [Blizzard/node-rdkafka#594]
**Environment Information**
 - Docker image node:8-stretch-slim 
 - Node Version 8.15.1
 - NPM Version 6.4.1
 - node-rdkafka version 2.6.1

**Steps to Reproduce**
`npm install --save node-rdkafka`

**Additional context**
```
root@01e83a1d6bb9:/app# npm install --save node-rdkafka

> node-rdkafka@2.6.1 install /app/node_modules/node-rdkafka
> node-gyp rebuild

module.js:550
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:653:30)
    at evalScript (bootstrap_node.js:479:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/node-rdkafka
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by sidharthv96** [comment]
Faced issues with `nan` when building on windows too.

```

> node-rdkafka@2.6.1 install <home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka
> node-gyp rebuild


<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka>if not defined npm_config_node_gyp (node "<home>\AppData\Roaming\nvm\v10.16.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "<home>\AppData\Roaming\nvm\v10.16.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Getting librdkafka from nuget
cl : Command line warning D9025: overriding '/GR-' with '/GR' [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
  binding.cc
  callbacks.cc
  common.cc
cl : Command line warning D9025: overriding '/GR-' with '/GR' [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
  config.cc
..\src\callbacks.cc(103): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxp
roj]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\callbacks.cc(275): error C2589: '(': illegal token on right side of '::' [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
..\src\callbacks.cc(275): error C2059: syntax error: '::' [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
..\src\callbacks.cc(575): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxp
roj]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\callbacks.cc(612): warning C4996: 'Nan::Callback::operator ()': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkaf
ka.vcxproj]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1638): note: see declaration of 'Nan::Callback::operator ()'
  connection.cc
  errors.cc
  kafka-consumer.cc
  producer.cc
<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\src/workers.h(42): warning C4996: 'Nan::Callback::Call': was declared deprecated (compiling source file ..\src\conn
ection.cc) [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call' (compiling source file ..\src\connection.cc)
<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\src/workers.h(42): warning C4996: 'Nan::Callback::Call': was declared deprecated (compiling source file ..\src\kafk
a-consumer.cc) [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call' (compiling source file ..\src\kafka-consumer.cc)
..\src\kafka-consumer.cc(560): warning C4996: 'v8::Value::ToObject': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka
.vcxproj]
  <home>\.node-gyp\10.16.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
..\src\kafka-consumer.cc(567): warning C4996: 'v8::Value::ToObject': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka
.vcxproj]
  <home>\.node-gyp\10.16.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
  topic.cc
  workers.cc
<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\src/workers.h(42): warning C4996: 'Nan::Callback::Call': was declared deprecated (compiling source file ..\src\prod
ucer.cc) [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call' (compiling source file ..\src\producer.cc)
..\src\producer.cc(115): warning C4996: 'v8::Value::ToObject': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpr
oj]
  <home>\.node-gyp\10.16.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
..\src\producer.cc(122): warning C4996: 'v8::Value::ToObject': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpr
oj]
  <home>\.node-gyp\10.16.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
..\src\producer.cc(373): warning C4996: 'v8::Value::ToObject': was declared deprecatedadmin.cc [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkaf
ka.vcxproj]

  <home>\.node-gyp\10.16.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
..\src\producer.cc(396): warning C4996: 'v8::Value::ToObject': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpr
oj]
  <home>\.node-gyp\10.16.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
  win_delay_load_hook.cc
..\src\topic.cc(118): warning C4996: 'v8::Value::ToObject': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
  <home>\.node-gyp\10.16.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\src/workers.h(42): warning C4996: 'Nan::Callback::Call': was declared deprecated (compiling source file ..\src\work
ers.cc) [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call' (compiling source file ..\src\workers.cc)
..\src\workers.cc(69): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj
]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(78): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj
]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(116): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(127): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(174): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(183): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(223): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(232): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(261): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(301): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(342): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(351): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(386): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(397): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(446): warning C4996: '_sleep': This function or variable has been superceded by newer library or operating system functionality. Consider using Sleep instead. See online help for deta
ils. [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdlib.h(1274): note: see declaration of '_sleep'
..\src\workers.cc(457): warning C4996: '_sleep': This function or variable has been superceded by newer library or operating system functionality. Consider using Sleep instead. See online help for deta
ils. [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdlib.h(1274): note: see declaration of '_sleep'
..\src\workers.cc(484): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(498): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(580): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(597): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(644): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(653): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(696): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(705): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(758): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(767): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(805): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(814): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'<home>\dev\webhooks-service\lifecycle-service\nod
  e_modules\node-rdkafka\src/workers.h(42): warning C4996: 'Nan::Callback::Call': was declared deprecated (compiling source file ..\src\admin.cc)

  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call' (compiling source file ..\src\admin.cc)..\src\workers.cc(852):
   warning C4996: 'Nan::Callback::Call': was declared deprecated

  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(861): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\workers.cc(900): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
..\src\admin.cc(111): warning C4996: 'v8::Value::ToObject': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
  <home>\.node-gyp\10.16.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
..\src\workers.cc(909): warning C4996: 'Nan::Callback::Call': was declared deprecated [<home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
  <home>\dev\webhooks-service\lifecycle-service\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (<home>\AppData\Roaming\nvm\v10.16.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "<home>\\AppData\\Roaming\\nvm\\v10.16.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd <home>\dev\webhooks-service\lifecycle-service\node_modules\node-rdkafka
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rdkafka@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
