### ISSUE TITLE
an unhandledRejection is emitted

### ISSUE THREAD

**Issue by NeoyeElf** [Blizzard/node-rdkafka#738]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: CentOS
 - Node Version [e.g. 8.2.1]: 8.9.1
 - node-rdkafka version [e.g. 2.3.3]: 2.7.4

**Steps to Reproduce**

**After I upgrade node-rdkafka from 2.2.1 to 2.7.4**, my program emit the unhandledRejection from time to time. The error message is:

```
 Promise {\n  <rejected> { Error: Local: Broker transport failure\n    at Function.createLibrdkafkaError [as create] (/data/node_modules/node-rdkafka/lib/error.js:334:10)\n    at /data/node_modules/node-rdkafka/lib/kafka-consumer.js:448:29\n  message: 'Local: Broker transport failure',\n  code: -195,\n  errno: -195,\n  origin: 'kafka' } } reason: { Error: Local: Broker transport failure\n    at Function.createLibrdkafkaError [as create] (/data/node_modules/node-rdkafka/lib/error.js:334:10)\n    at /data/node_modules/node-rdkafka/lib/kafka-consumer.js:448:29\n  message: 'Local: Broker transport failure',\n  code: -195,\n  errno: -195,\n  origin: 'kafka' }
```

And I have handled `event.error`.

**node-rdkafka Configuration Settings**

```
new Kafka.KafkaConsumer(
  {
    'group.id': 'xxx',
    'metadata.broker.list': 'xxx',
    'enable.auto.commit': false,
    'fetch.message.max.bytes': 67108864,
    'message.max.bytes': 67108864,
    'session.timeout.ms': 10000,
    'fetch.wait.max.ms': 20,
    rebalance_cb: function(err, assignment) {
      if (err.code === Kafka.CODES.ERRORS.ERR__ASSIGN_PARTITIONS) {
        // Note: this can throw when you are disconnected. Take care and wrap it in
        // a try catch if that matters to you
        this.assign(assignment);
      } else if (err.code == Kafka.CODES.ERRORS.ERR__REVOKE_PARTITIONS){
        // Same as above
        this.unassign();
      } else {
        // We had a real error
        console.error(err);
      }

    },
    event_cb: true,
  },
  {
     'auto.offset.reset': 'earliest'
  }
)
```

Is there any errors that have not been catch?

**Comment by NeoyeElf** [comment]
After I catch the error throws by `KafkaConsumer.consume()` , the unhandledRejection is gone. closing it.
