### ISSUE TITLE
node:lts and node:lts-buster libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ceastman-ibm** [Blizzard/node-rdkafka#750]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: node:lts (debian stretch) and node:lts-buster
 - Node Version [e.g. 8.2.1]: ~12.14
 - NPM Version [e.g. 5.4.2]: 6.13.4
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: gcc
 - node-rdkafka version [e.g. 2.3.3]: 2.7.4

**Steps to Reproduce**
build the microservice with node-rdkafka, zip up node modules, deploy the zip to a clean node:lts 

**node-rdkafka Configuration Settings**
default settings

**Additional context**

these are the only libssl.so files in the image:
/usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
/usr/lib/x86_64-linux-gnu/libssl.so.1.1

here is the stack trace when starting the microservice:
/home/node/app/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: libssl.so.1.0.0: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/home/node/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/node/app/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/node/app/node_modules/node-rdkafka/lib/client.js:14:13)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/node/app/node_modules/node-rdkafka/lib/kafka-consumer.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:955:30)

**Comment by ceastman-ibm** [comment]
Looking through the closed issues there was mention of removing libssl-dev and installing libssl1.0-dev but i get the following error:
Package libssl1.0-dev is not available, but is referred to by another package.

can node-rdkafka not use the openssl 1.1 version?

**Comment by codeburke** [comment]
node-rdkafka doesn't use any of the SSL modules directly, AFAIK. They are all dependencies of [librdkafka](https://github.com/edenhill/librdkafka). It might be worth opening an Issue there and cross referencing to this Issue.

**Comment by ceastman-ibm** [comment]
I believe i found the issue, zip is not zipping up the softlinks. i found this by switching to gzip:
gzip: ./node_modules/node-rdkafka/build/deps/librdkafka.so: Too many levels of symbolic links
