### ISSUE TITLE
Error: `gyp` failed with exit code: 1 during yarn install

### ISSUE THREAD

**Issue by Dalfons0** [Blizzard/node-rdkafka#771]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Ubuntu 19.10
 - Node Version [e.g. 8.2.1]: v10.19.0
 - NPM Version [e.g. 5.4.2]: 6.13.4
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]: v2.7.4

**Steps to Reproduce**
I'm trying to install it using yarn instead of npm but the error is the same in both package managers.
I also tried to install with the current (v13.12.0) and lts (v12.16.1), but without more luck and I'm using the specified node version as is the same used in my deploy environment.

**Additional context**
```
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > tslint-config-airbnb@5.11.2" has incorrect peer dependency "tslint@^5.11.0".
warning "tslint-config-airbnb > tslint-consistent-codestyle@1.16.0" has incorrect peer dependency "tslint@^5.0.0".
warning "tslint-config-airbnb > tslint-eslint-rules@5.4.0" has incorrect peer dependency "tslint@^5.0.0".
warning "tslint-config-airbnb > tslint-microsoft-contrib@5.2.1" has incorrect peer dependency "tslint@^5.1.0".
warning "tslint-config-airbnb > tslint-consistent-codestyle > @fimbul/bifrost@0.21.0" has incorrect peer dependency "tslint@^5.0.0".
[4/4] Building fresh packages...
[7/8] ⠐ husky
[-/8] ⠐ waiting...
[3/8] ⠐ node-rdkafka
[-/8] ⠐ waiting...
error /home/dalgar/Projects/LECMultitenant/node_modules/node-rdkafka: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/dalgar/Projects/LECMultitenant/node_modules/node-rdkafka
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@10.19.0 | linux | x64
gyp info find Python using Python version 3.7.5 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [ '/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/dalgar/Projects/LECMultitenant/node_modules/node-rdkafka/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/dalgar/.cache/node-gyp/10.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/dalgar/.cache/node-gyp/10.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/dalgar/.cache/node-gyp/10.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/dalgar/Projects/LECMultitenant/node_modules/node-rdkafka',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2215, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 794, in Write
    extra_mac_bundle_resources, part_of_all)
  File "/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 978, in WriteActions
    part_of_all=part_of_all, command=name)
  File "/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1724, in WriteDoCmd
    force = True)
  File "/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1779, in WriteMakeRule
    cmddigest = hashlib.sha1(command if command else self.target).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.3.0-45-generic
gyp ERR! command "/home/dalgar/.nvm/versions/node/v10.19.0/bin/node" "/home/dalgar/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dalgar/Projects/LECMultitenant/node_modules/node-rdkafka
```

**Comment by Dalfons0** [comment]
Solved installing again python, so this worked after running `sudo apt-get install -y python`, which is weird because the stack trace says `using Python version 3.7.5 found at "/usr/bin/python3"`...
