### ISSUE TITLE
connect fail in ubuntu.

### ISSUE THREAD

**Issue by huenchao** [Blizzard/node-rdkafka#779]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: ubuntu-18.04
 - Node Version [e.g. 8.2.1]: v10.x
 - NPM Version [e.g. 5.4.2]: v6.x
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]: 2.8.0

**Steps to Reproduce**
connect to server, callbacks return a err which reports message as follow:
```javascript
{ Error: No provider for SASL mechanism SCRAM-SHA-256: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN
    at Function.createLibrdkafkaError [as create] (/src/node_modules/node-rdkafka/lib/error.js:402:10)
    at /src/node_modules/node-rdkafka/lib/client.js:187:28
  message:
   'No provider for SASL mechanism SCRAM-SHA-256: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN',
  code: -172,
  errno: -172,
  origin: 'kafka' }
```
**node-rdkafka Configuration Settings**
```javascript
var producer = new Kafka.Producer({
    'metadata.broker.list': '****',
    'sasl.username':'****',
    'sasl.password': '****',
    'sasl.mechanisms': 'SCRAM-SHA-256',
    'security.protocol': 'sasl_plaintext',
    'group.id': 'handsOfDavinciProducerGroup',
    'client.id': 'hands-of-davinci'
});
      producer.connect({ topic: this.topicName, timeout: 5000 }, (err: any, data: any) => {
        if (err) {
          console.log('connect err ', err);
        }
        if (data) {
          console.log('connect data ', data);
        }

      });
```
**Additional context**

**Comment by huenchao** [comment]
when i try those code on macos， it works。what's wrong with it?

**Comment by henningms** [comment]
Have you tried installing libsasl2-dev (and eventually librdkafka-dev)?

`sudo apt-get install -y librdkafka-dev libsasl2-dev`
