### ISSUE TITLE
Inconsistent results when deploying on docker (metadata fails) Error: Local: Broker transport failure

### ISSUE THREAD

**Issue by RobinGoussey** [Blizzard/node-rdkafka#781]
**Environment Information**
 - node:10-alpine (raspberry pi)
 - Node Version [e.g. 8.2.1]: v10.20.1
 - NPM Version [e.g. 5.4.2]: 6.14.4

docker file:
```
FROM node:10-alpine as build

RUN apk --no-cache add \
      bash \
      g++ \
      ca-certificates \
      lz4-dev \
      musl-dev \
      cyrus-sasl-dev \
      openssl-dev \
      make \
      python \
      bluez curl cmake \
      && apk add --no-cache --virtual .build-deps gcc zlib-dev libc-dev bsd-compat-headers py-setuptools 
.... <the rest omitted>
```

**Steps to Reproduce**
This is a piece of code (I didn't write it), however, it works sometimes, sometimes it doesnt.
```
class KafkaAvroProducer {
  constructor(kafkaBroker, schemaRegistry, kafkaConfig) {
    this.client = KafkaAvroProducer.getKafkaClient(kafkaBroker, schemaRegistry);
    this.kafkaConfig = kafkaConfig;
    this.kafkaBroker = kafkaBroker;
    this.schemaRegistry = schemaRegistry;
  }

  async initAvroProducer() {
    await KafkaAvroProducer.initialiseKafkaClient(this.client);
    this.producer = await KafkaAvroProducer.getKafkaProducer(this.client, this.kafkaConfig);
    this.producer.setPollInterval(10);
    this.setupEventHandlers();
    console.log(`KafkaAvroProducer intialized for broker ${this.kafkaBroker} and schema registry ${this.schemaRegistry}`);
  }

  /**
   *  Kafka Client
   */
  static getKafkaClient(kafkaBroker, schemaRegistry) {
    return new KafkaAvro({
      kafkaBroker: kafkaBroker,
      schemaRegistry: schemaRegistry,
      wrapUnions: false,
      fetchAllVersions: true,
    });
  }

  static async initialiseKafkaClient(client) {
    await client.init();
  }

  /**
    * Kafka Producer
    */
  static async getKafkaProducer(client,kafkaConfig) {
    return client.getProducer(kafkaConfig, {
      // -1 = All ISR's of broker respond
      'request.required.acks': -1,
      'message.timeout.ms': 5000
    });
  }

}

export default KafkaAvroProducer;
```

**node-rdkafka Configuration Settings**
```
{ 'queue.buffering.max.messages': 100000,
2020-04-15T10:25:55.496417360Z     dr_msg_cb: true,
2020-04-15T10:25:55.496444444Z     'message.send.max.retries': 10000000,
2020-04-15T10:25:55.496469964Z     'message.timeout.ms': 5000,
2020-04-15T10:25:55.496494860Z     'sasl.mechanisms': 'PLAIN',
2020-04-15T10:25:55.496519756Z     'security.protocol': 'SASL_SSL',
2020-04-15T10:25:55.496544964Z     'ssl.ca.location': '<omitted>',
2020-04-15T10:25:55.496570433Z     'sasl.username': '<omitted>',
2020-04-15T10:25:55.496595277Z     'sasl.password': '<omitted>',
2020-04-15T10:25:55.496620381Z     'metadata.broker.list': '<omitted>' }
```
**Additional context**
After switching to sasl, ssl, we got an inconsistent error. So we use (avro) node-rdkafka for communication with a local kafka. However, on some machines it works perfectly, on some it never works. What I've checked:
- On both (a machine that works and one that doesn't work), we have exactly the same installed packages, on the host, and the docker images.
- Both have exactly the same docker image, and config files.
- The client object is exactly the same. (console.log from node_modules).

So I figure this might be an network or configuration error. After digging in the node_module, I figured out that there is an error with getting the metadata from the broker. However, both can reach the broker just fine. They have a ping between 5 and 7 ms. 

Problem is, there are a lot of the broker failure issues etc on the internet, but non seem to describe/solve this. I hope I gave enough context, otherwise, let me know.

The resulting error:
```
[2020-02-19T09:37:57.166Z] ERROR: KafkaAvro/29 on ...: getProducer() :: Connect failed: (module=/kafka-producer.js)
2020-02-19T09:37:57.169703128Z   Error: Local: Broker transport failure
2020-02-19T09:37:57.169780419Z       at Function.createLibrdkafkaError [as create] (/usr/src/app/node_modules/node-rdkafka/lib/error.js:334:10)
2020-02-19T09:37:57.169842659Z       at /usr/src/app/node_modules/node-rdkafka/lib/client.js:340:28
2020-02-19T09:37:57.175829013Z { Error: Local: Broker transport failure
2020-02-19T09:37:57.176010211Z     at Function.createLibrdkafkaError [as create] (/usr/src/app/node_modules/node-rdkafka/lib/error.js:334:10)
2020-02-19T09:37:57.176309274Z     at /usr/src/app/node_modules/node-rdkafka/lib/client.js:340:28
2020-02-19T09:37:57.176378753Z   origin: 'local',
2020-02-19T09:37:57.176438440Z   message: 'broker transport failure',
2020-02-19T09:37:57.176499378Z   code: -195,
2020-02-19T09:37:57.176557867Z   errno: -195,
2020-02-19T09:37:57.176687138Z   stack:
2020-02-19T09:37:57.176750159Z    'Error: Local: Broker transport failure\n    at Function.createLibrdkafkaError [as create] (/usr/src/app/node_modules/node-rdkafka/lib/error.js:334:10)\n    at /usr/src/app/node_modules/node-rdkafka/lib/client.js:340:28' }
```

**Comment by RobinGoussey** [comment]
Update:
We reversed the Kafka SASL SSL, and now all of them work again, we haven't found out why the sometimes it does work, and sometimes it doesn't. Only thing we did, was change the config (and set the server up for plaintext again).

New config:
```
{ 'queue.buffering.max.messages': 100000,
2020-04-15T10:25:55.496417360Z     dr_msg_cb: true,
2020-04-15T10:25:55.496444444Z     'message.send.max.retries': 10000000,
2020-04-15T10:25:55.496469964Z     'message.timeout.ms': 5000}
```

**Comment by RobinGoussey** [comment]
Ok, so after a bit more experience, I've figured out what causes these errors. The local broker transport failure usually occurs whenever I use the wrong url or give wrong credentials.
Eg. https, when it should be http, I used https, or when it should be https, I gave the wrong credentials
