### ISSUE TITLE
Cannot get any message 

### ISSUE THREAD

**Issue by SHwan93** [Blizzard/node-rdkafka#785]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: OSX
 - Node Version [e.g. 8.2.1]: v12.13.0
 - NPM Version [e.g. 5.4.2]:6.14.4
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: vscode
 - node-rdkafka version [e.g. 2.3.3]: 2.8.1

**Steps to Reproduce**

**node-rdkafka Configuration Settings**

**Additional context**

```js

const kafka = require("node-rdkafka");

const consumer = new kafka.KafkaConsumer(
  {
    // debug: "all",
    "metadata.broker.list": "192.168.0.4:9092",
    "group.id": "mysterico",
    "partition.assignment.strategy": "roundrobin",
    "session.timeout.ms": 10000,
    "heartbeat.interval.ms": 3000,
    "group.protocol.type": "consumer",
     "max.poll.interval.ms": 300000,
    "enable.auto.commit": true,
    "auto.commit.interval.ms": 3000,
    rebalance_cb: function (err, assignment) {
      if (err) {
        console.log(err);
      }
      console.log("REBALANCED : ", assignment);
    },
    offset_commit_cb: function (err, topicPartitions) {
      if (err) {
        console.log(err);
      }
      console.log("COMMITED : ", topicPartitions);
    },
  },
  {
    "auto.offset.reset": "latest",
  }
);

consumer.connect({}, (err, data) => {
  if (err) {
    console.log(err);
  }

  console.log("CONNECT : ", data);
});

/**
 * The ready event is emitted when the Consumer is ready to read messages.
 */
consumer.on("ready", (clientId) => {
  consumer.subscribe(["test"]);

  // // Consume from the librdtesting-01 topic. This is what determines
  // // the mode we are running in. By not specifying a callback (or specifying
  // // only a callback) we get messages as soon as they are available.
  consumer.consume();
});
/**
 * When using the Standard API consumed messages are emitted in this event.
 */
consumer.on("data", function (data) {
  // Output the actual message contents
  console.log(data.value.toString());
});
consumer.on("connection.failure", () => {
  console.log("1");
});
consumer.on("event.error", (error) => {
  console.log("2 ", error);
});
consumer.on("event.stats", () => {
  console.log("3");
});
consumer.on("event.log", (log) => {
  console.log("4 ", log);
});
consumer.on("event.event", () => {
  console.log("5");
});
consumer.on("event.throttle", () => {
  console.log("6");
});
consumer.on("event.disconnected", () => {
  console.log("7");
});


```

![image](https://user-images.githubusercontent.com/36143374/80086998-75ba8200-8595-11ea-96cc-7359e305bd8c.png)

![image](https://user-images.githubusercontent.com/36143374/80087209-c4681c00-8595-11ea-91e3-baef47a725ee.png)

**Comment by SHwan93** [comment]
i remove below code. so now is working well 

```js
rebalance_cb: function (err, assignment) {
      if (err) {
        console.log(err);
      }
      console.log("REBALANCED : ", assignment);
    },

```

But i don't know why.

**Comment by SHwan93** [comment]
```js
LibrdKafkaError: Local: Assign partitions
    at Function.createLibrdkafkaError [as create] (/Users/ian/workspace/mysterico/sample_kafka_consumer/node_modules/node-rdkafka/lib/error.js:402:10)
    at KafkaConsumer.conf.rebalance_cb (/Users/ian/workspace/mysterico/sample_kafka_consumer/node_modules/node-rdkafka/lib/kafka-consumer.js:83:36) {
  message: 'Local: Assign partitions',
  code: -175,
  errno: -175,
  origin: 'kafka'
}
```

i think it is cause

**Comment by iradul** [comment]
Since you're using `rebalance_cb` function you have to handle rebalancing manually hence you have to call `assign` method:
```js
    rebalance_cb: function (err, assignment) {
      if (err) {
        console.log(err);
      }
      console.log("REBALANCED : ", assignment);
      consumer.assign(assignment); // you need to make this call
    },
```

**Comment by SHwan93** [comment]
Now I understand that phrase can occur naturally, not in error.
