### ISSUE TITLE
Unit tests fail on ppc64le

### ISSUE THREAD

**Issue by seth-priya** [Blizzard/node-rdkafka#805]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: IBM Linux on Power, RHEL 7.8 (ppc64le)
 - Node Version [e.g. 8.2.1]: v8.14.0
 - NPM Version [e.g. 5.4.2]:6.4.1
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
 - node-rdkafka version [e.g. 2.3.3]: master

**Steps to Reproduce**
npm install; make test
**node-rdkafka Configuration Settings**
None

**Additional context**
Tests fail with the below error
 make check
/root/Priya/node-rdkafka/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /node-rdkafka/build/node-librdkafka.node
 → /node-rdkafka/build/Debug/node-librdkafka.node
 → /node-rdkafka/build/Release/node-librdkafka.node
 → /node-rdkafka/out/Debug/node-librdkafka.node
 → /node-rdkafka/Debug/node-librdkafka.node
 → /node-rdkafka/out/Release/node-librdkafka.node
 → /node-rdkafka/Release/node-librdkafka.node
 → /node-rdkafka/build/default/node-librdkafka.node
 → /node-rdkafka/compiled/8.14.0/linux/ppc64/node-librdkafka.node
 → /node-rdkafka/addon-build/release/install-root/node-librdkafka.node
 → /node-rdkafka/addon-build/debug/install-root/node-librdkafka.node
 → /node-rdkafka/addon-build/default/install-root/node-librdkafka.node
 → /node-rdkafka/lib/binding/node-v57-linux-ppc64/node-librdkafka.node
    at bindings (/node-rdkafka/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node-rdkafka/lib/client.js:14:13)

Any pointers on how to debug this would be of great help, thank you!

**Comment by seth-priya** [comment]
I was trying to run the build with root user in container, switching to non-root user resolved the issue
