### ISSUE TITLE
`npm install` of 2.9.0 fails on node 10.15.3

### ISSUE THREAD

**Issue by fluffywaffles** [Blizzard/node-rdkafka#807]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: arch linux
 - Node Version [e.g. 8.2.1]: 10.15.3
 - NPM Version [e.g. 5.4.2]: 6.4.1
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: gcc
 - node-rdkafka version [e.g. 2.3.3]: 2.9.0

**Steps to Reproduce**
```
$ nvm use 10.15
$ npm install node-rdkafka@latest
```

**node-rdkafka Configuration Settings**

**Additional context**
```
make[1]: Leaving directory /home/fluffywaffles/dev/better/@better/events/node_modules/node-rdkafka/deps/librdkafka
  TOUCH Release/obj.target/deps/librdkafka.stamp
  CXX(target) Release/obj.target/node-librdkafka/src/binding.o
In file included from /home/fluffywaffles/dev/better/@better/events/node_modules/node-rdkafka/src/binding.h:13,
                 from ../src/binding.cc:11:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:7: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2294 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc: In function ‘void Init(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’:
../src/binding.cc:81:34: error: ‘GetCurrentEnvironment’ is not a member of ‘node’; did you mean ‘CreateEnvironment’?
   81 |   node::Environment* env = node::GetCurrentEnvironment(context);
      |                                  ^~~~~~~~~~~~~~~~~~~~~
      |                                  CreateEnvironment
In file included from /home/fluffywaffles/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from /home/fluffywaffles/dev/better/@better/events/node_modules/node-rdkafka/src/binding.h:13,
                 from ../src/binding.cc:11:
/home/fluffywaffles/.node-gyp/10.15.3/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/fluffywaffles/.node-gyp/10.15.3/include/node/node_object_wrap.h:85:78:   required from here
/home/fluffywaffles/.node-gyp/10.15.3/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/fluffywaffles/.node-gyp/10.15.3/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/fluffywaffles/.node-gyp/10.15.3/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [node-librdkafka.target.mk:120: Release/obj.target/node-librdkafka/src/binding.o] Error 1
rm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
make: Leaving directory /home/fluffywaffles/dev/better/@better/events/node_modules/node-rdkafka/build
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/fluffywaffles/.config/nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.6.15-arch1-1
gyp ERR! command "/home/fluffywaffles/.config/nvm/versions/node/v10.15.3/bin/node" "/home/fluffywaffles/.config/nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fluffywaffles/dev/better/@better/events/node_modules/node-rdkafka
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN @better/events@0.2.3 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rdkafka@2.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fluffywaffles/.npm/_logs/2020-06-16T17_10_31_236Z-debug.log
```
related: https://github.com/Blizzard/node-rdkafka/issues/806

comment stated "[works against node 10](https://github.com/Blizzard/node-rdkafka/issues/806#issuecomment-644788141)", but I want to point out this may only be true for certain releases in the node 10 LTS series, and it is not true for versions in the `10.15.x` range.

Perhaps a similar fix as for node 9 can be applied for node 10.

**Comment by iradul** [comment]
You are correct only [`10.16.0`](https://github.com/nodejs/node/releases/tag/v10.16.0) and up can compile because of this:
`[c2dab8e642] - (SEMVER-MINOR) src,test: add public wrapper for Environment::GetCurrent (Shelley Vohr) #23676`

**Comment by iradul** [comment]
Let's move this to #806
