### ISSUE TITLE
npm install node-rdkafka hangs on node-gyp rebuild with deps/librdkafka.target.mk:13: recipe for target 'deps/librdkafka/config.h' failed

### ISSUE THREAD

**Issue by RicardoGralhoz** [Blizzard/node-rdkafka#825]
**Environment Information**
OS: Ubuntu 18.04.2 LTS
Node:  v10.13.0 LTS
NPM Version : 6.4.1
C++ Toolchain : g++
node-rdkafka version: 2.9.0

**Steps to Reproduce**
1. On the CLI, run
```
cd /home/auser/versions/app/node_modules
npm install node-rdkafka --loglevel="verbose"
```

#### Output
```
npm info it worked if it ends with ok
npm verb cli [ '/home/auser/versions/node-v10.13.0/bin/node',
npm verb cli   '/home/auser/node/bin/npm',
npm verb cli   'install',
npm verb cli   'node-rdkafka',
npm verb cli   '--loglevel=verbose' ]
npm info using npm@6.4.1
npm info using node@v10.13.0
npm verb npm-session c1ea12ed
npm http fetch GET 304 https://registry.npmjs.org/node-rdkafka 126ms (from cache)
npm timing stage:loadCurrentTree Completed in 882ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 3ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 118ms
npm http fetch GET 304 https://registry.npmjs.org/nan 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bindings 238ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/file-uri-to-path 55ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 510ms
npm timing stage:loadIdealTree Completed in 711ms
npm timing stage:generateActionsToTake Completed in 23ms
npm verb correctMkdir /home/auser/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/auser/.npm/_locks/staging-bf8cf57ec5c55454.lock for /home/auser/versions/app/node_modules/.staging
npm timing audit compress Completed in 8ms
npm info audit Submitting payload of 22296bytes
npm timing action:extract Completed in 214ms
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm timing action:unbuild Completed in 2ms
npm timing action:remove Completed in 0ms
npm timing action:finalize Completed in 5ms
npm timing action:refresh-package-json Completed in 68ms
npm info lifecycle file-uri-to-path@1.0.0~preinstall: file-uri-to-path@1.0.0
npm info lifecycle bindings@1.5.0~preinstall: bindings@1.5.0
npm info lifecycle nan@2.14.1~preinstall: nan@2.14.1
npm info lifecycle node-rdkafka@2.9.0~preinstall: node-rdkafka@2.9.0
npm timing action:preinstall Completed in 2ms
npm info linkStuff file-uri-to-path@1.0.0
npm info linkStuff bindings@1.5.0
npm info linkStuff nan@2.14.1
npm info linkStuff node-rdkafka@2.9.0
npm timing action:build Completed in 2ms
npm info lifecycle file-uri-to-path@1.0.0~install: file-uri-to-path@1.0.0
npm info lifecycle bindings@1.5.0~install: bindings@1.5.0
npm info lifecycle nan@2.14.1~install: nan@2.14.1
npm info lifecycle node-rdkafka@2.9.0~install: node-rdkafka@2.9.0

> node-rdkafka@2.9.0 install /home/auser/versions/app/node_modules/node-rdkafka
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/home/auser/versions/node-v10.13.0/bin/node',
gyp verb cli   '/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.13.0
gyp verb command install [ '10.13.0' ]
gyp verb install input version string "10.13.0"
gyp verb install installing version: 10.13.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.13.0
gyp verb build dir attempting to create "build" dir: /home/auser/versions/app/node_modules/node-rdkafka/build
gyp verb build dir "build" dir needed to be created? /home/auser/versions/app/node_modules/node-rdkafka/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/auser/versions/app/node_modules/node-rdkafka/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/auser/versions/app/node_modules/node-rdkafka/config.gypi
gyp verb common.gypi checking for gypi file: /home/auser/versions/app/node_modules/node-rdkafka/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/auser/versions/app/node_modules/node-rdkafka/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/auser/.node-gyp/10.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/auser/.node-gyp/10.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/auser/.node-gyp/10.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/auser/versions/app/node_modules/node-rdkafka',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/auser/.node-gyp/10.13.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/auser/versions/app/node_modules/node-rdkafka/build'
  LD_LIBRARY_PATH=/home/auser/versions/app/node_modules/node-rdkafka/build/Release/lib.host:/home/auser/versions/app/node_modules/node-rdkafka/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps; mkdir -p librdkafka; node ../util/configure
checking for OS or distribution... ok (ubuntu)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking executable libtool... failed (disable)
checking for pkgconfig (by command)... failed
checking for install (by command)...
```
_**it hangs here; then pressing ^C**_
```
^Cdeps/librdkafka.target.mk:13: recipe for target 'deps/librdkafka/config.h' failed
make: *** [deps/librdkafka/config.h] Interrupt
npm verb lifecycle node-rdkafka@2.9.0~install: unsafe-perm in lifecycle true
npm verb lifecycle node-rdkafka@2.9.0~install: PATH: /home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/auser/versions/app/node_modules/node-rdkafka/node_modules/.bin:/home/auser/versions/app/node_modules/.bin:/home/auser/node/bin:/home/auser/bin:/home/auser/app/utils:/home/auser/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npm verb lifecycle node-rdkafka@2.9.0~install: CWD: /home/auser/versions/app/node_modules/node-rdkafka
```
**node-rdkafka Configuration Settings**

**Additional context**
_Using a previously working system that had **node-rdkafka v2.3.4** and **librdkafka v0.11.4**, with a change in the initialization of OpenSSL on `rdkafka_transport.c` to use `TLS_client_method()` instead of `SSLv23_client_method()`_  

The same issue also happens on trying to install node-rdkafka with different versions or on a different folder.

**Comment by RicardoGralhoz** [comment]
If reverting to the previous VM snapshot and trying to run instead, ultimately I get the same results

1. `npm update node-rdkafka --loglevel="verbose"`
2. _Error: Refusing to delete /home/auser/versions/app/node_modules/datejs/node_modules/.bin/vows: is outside /home/auser/versions/app/node_modules/datejs/node_modules/vows and not a link_
3. `rm /home/auser/versions/app/node_modules/datejs/node_modules/.bin/vows`
4. `npm update node-rdkafka --loglevel="verbose"`
5. it hangs

---

### Output Logs for Step 1 above:
```
npm info it worked if it ends with ok
npm verb cli [ '/home/auser/versions/node-v10.13.0/bin/node',
npm verb cli   '/home/auser/node/bin/npm',
npm verb cli   'update',
npm verb cli   'node-rdkafka',
npm verb cli   '--loglevel=verbose' ]
npm info using npm@6.4.1
npm info using node@v10.13.0
npm verb npm-session c1ea12ed
npm verb update computing outdated modules to update
npm verb request uri https://registry.npmjs.org/node-rdkafka
npm verb request no auth needed
npm info attempt registry request try #1 at 2:21:07 PM
npm verb request id c1ea12ed2
npm http request GET https://registry.npmjs.org/node-rdkafka
npm http 200 https://registry.npmjs.org/node-rdkafka
npm verb headers { date: 'Wed, 22 Jul 2020 21:21:08 GMT',
npm verb headers   'content-type': 'application/json',
npm verb headers   'transfer-encoding': 'chunked',
npm verb headers   connection: 'keep-alive',
npm verb headers   'set-cookie':
... [extra logs removed ]
npm verb headers   'content-encoding': 'gzip' }
npm info outdated updating [ { dep:
npm info outdated      Node {
npm info outdated        name: 'node-rdkafka',
npm info outdated        path:
npm info outdated         '/home/auser/versions/app/node_modules/node-rdkafka',
npm info outdated        realpath:
npm info outdated         '/home/auser/versions/app/node_modules/node-rdkafka',
npm info outdated        error: null,
npm info outdated        id: 41,
npm info outdated        package: [Object],
npm info outdated        parent: [Node],
npm info outdated        isLink: false,
npm info outdated        children: [Array],
npm info outdated        loaded: false,
npm info outdated        requiredBy: [],
npm info outdated        requires: [Array],
npm info outdated        missingDeps: {},
npm info outdated        missingDevDeps: {},
npm info outdated        phantomChildren: {},
npm info outdated        location: '/node-rdkafka',
npm info outdated        userRequired: false,
npm info outdated        save: false,
npm info outdated        saveSpec: null,
npm info outdated        isTop: false,
npm info outdated        fromBundle: false,
npm info outdated        isInLink: false },
npm info outdated     depname: 'node-rdkafka',
npm info outdated     current: '2.3.4',
npm info outdated     wanted: '2.9.0',
npm info outdated     latest: '2.9.0',
npm info outdated     req: '^2.3.4',
npm info outdated     what: 'node-rdkafka@2.9.0' } ]
npm http fetch GET 200 https://registry.npmjs.org/node-rdkafka 212ms
npm http fetch GET 200 https://registry.npmjs.org/node-rdkafka/-/node-rdkafka-2.9.0.tgz 299ms
npm timing stage:loadCurrentTree Completed in 1027ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 4ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 65ms
npm http fetch GET 200 https://registry.npmjs.org/bindings 31ms
npm http fetch GET 200 https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz 25ms
npm http fetch GET 200 https://registry.npmjs.org/nan 88ms
npm http fetch GET 200 https://registry.npmjs.org/nan/-/nan-2.14.1.tgz 34ms
npm http fetch GET 200 https://registry.npmjs.org/file-uri-to-path 27ms
npm http fetch GET 200 https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz 25ms
npm http fetch GET 200 https://registry.npmjs.org/vows 127ms
npm http fetch GET 200 https://registry.npmjs.org/vows/-/vows-0.6.3.tgz 38ms
npm http fetch GET 200 https://registry.npmjs.org/eyes 25ms
npm http fetch GET 200 https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz 30ms
... [extra logs removed ]
npm http fetch GET 200 https://registry.npmjs.org/lodash 26ms
npm http fetch GET 200 https://registry.npmjs.org/lodash/-/lodash-3.5.0.tgz 45ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 3121ms
npm timing stage:loadIdealTree Completed in 3269ms
npm timing stage:generateActionsToTake Completed in 31ms
npm verb correctMkdir /home/auser/.npm/_locks correctMkdir not in flight; initializing
npm verb makeDirectory /home/auser/.npm/_locks creation not in flight; initializing
npm timing audit compress Completed in 3ms
npm info audit Submitting payload of 21707bytes
npm verb lock using /home/auser/.npm/_locks/staging-bf8cf57ec5c55454.lock for /home/auser/versions/app/node_modules/.staging
npm timing audit submit Completed in 349ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 358ms
npm timing audit body Completed in 11ms
npm timing action:extract Completed in 728ms
npm info lifecycle node-rdkafka@2.3.4~preuninstall: node-rdkafka@2.3.4
npm info lifecycle node-rdkafka@2.3.4~uninstall: node-rdkafka@2.3.4
npm verb unbuild rmStuff node-rdkafka@2.3.4 from /home/auser/versions/app/node_modules
npm info lifecycle node-rdkafka@2.3.4~postuninstall: node-rdkafka@2.3.4
npm info lifecycle iconv-lite@0.2.11~preuninstall: iconv-lite@0.2.11
... [extra logs removed ]
npm verb unbuild rmStuff colors@0.6.0-1 from /home/auser/versions/app/node_modules
npm verb unbuild rmStuff in /home/auser/versions/app/node_modules/geoip-lite/node_modules
npm info lifecycle colors@0.6.0-1~postuninstall: colors@0.6.0-1
npm info lifecycle vows@0.6.3~preuninstall: vows@0.6.3
npm info lifecycle vows@0.6.3~uninstall: vows@0.6.3
npm verb unbuild rmStuff vows@0.6.3 from /home/auser/versions/app/node_modules
npm verb unbuild rmStuff in /home/auser/versions/app/node_modules/datejs/node_modules
npm timing action:unbuild Completed in 66ms
npm verb unlock done using /home/auser/.npm/_locks/staging-bf8cf57ec5c55454.lock for /home/auser/versions/app/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 5482ms
npm WARN enoent ENOENT: no such file or directory, open '/home/auser/versions/app/package.json'
npm verb enoent This is related to npm not being able to find a file.
npm verb enoent
npm WARN bootstrap@4.5.0 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN app No description
npm WARN app No repository field.
npm WARN app No README data
npm WARN app No license field.

npm verb stack Error: Refusing to delete /home/auser/versions/app/node_modules/datejs/node_modules/.bin/vows: is outside /home/auser/versions/app/node_modules/datejs/node_modules/vows and not a link
npm verb stack     at clobberFail (/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:121:12)
npm verb stack     at isSafeToRm (/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:114:15)
npm verb stack     at /home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:54:5
npm verb stack     at LOOP (/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
npm verb stack     at /home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
npm verb stack     at /home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:180:7
npm verb stack     at /home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/node_modules/iferr/index.js:13:50
npm verb stack     at _readAllLinks (/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:215:28)
npm verb stack     at /home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/node_modules/iferr/index.js:13:50
npm verb stack     at resolveSymlink (/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:226:22)
npm verb stack     at _readAllLinks (/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:217:5)
npm verb stack     at readAllLinks (/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:212:3)
npm verb stack     at /home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:179:5
npm verb stack     at /home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/node_modules/iferr/index.js:13:50
npm verb stack     at cb (/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm verb stack     at /home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:153:16
npm verb cwd /home/auser/versions/app
npm verb Linux 4.15.0-43-generic
npm verb argv "/home/auser/versions/node-v10.13.0/bin/node" "/home/auser/node/bin/npm" "update" "node-rdkafka" "--loglevel=verbose"
npm verb node v10.13.0
npm verb npm  v6.4.1
npm ERR! path /home/auser/versions/app/node_modules/datejs/node_modules/.bin/vows
npm ERR! code EEXIST
npm ERR! Refusing to delete /home/auser/versions/app/node_modules/datejs/node_modules/.bin/vows: is outside /home/auser/versions/app/node_modules/datejs/node_modules/vows and not a link
npm ERR! File exists: /home/auser/versions/app/node_modules/datejs/node_modules/.bin/vows
npm ERR! Move it away, and try again.
npm verb exit [ 1, true ]
npm timing npm Completed in 7589ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/auser/.npm/_logs/2020-07-22T21_21_13_751Z-debug.log
```

---

### Output Logs for Step 4 above:
```
... [logs removed]
info lifecycle iconv-lite@0.2.11~install: iconv-lite@0.2.11
npm info lifecycle bindings@1.5.0~install: bindings@1.5.0
npm info lifecycle nan@2.14.1~install: nan@2.14.1
npm info lifecycle node-rdkafka@2.9.0~install: node-rdkafka@2.9.0

> node-rdkafka@2.9.0 install /home/auser/versions/app/node_modules/node-rdkafka
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/home/auser/versions/node-v10.13.0/bin/node',
gyp verb cli   '/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.13.0
gyp verb command install [ '10.13.0' ]
gyp verb install input version string "10.13.0"
gyp verb install installing version: 10.13.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.13.0
gyp verb ensuring nodedir is created /home/auser/.node-gyp/10.13.0
gyp verb created nodedir /home/auser/.node-gyp
gyp http GET https://nodejs.org/download/release/v10.13.0/node-v10.13.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.13.0/node-v10.13.0-headers.tar.gz
gyp verb extracted file from tarball include/node/common.gypi
gyp verb extracted file from tarball include/node/config.gypi
gyp verb extracted file from tarball include/node/node.h
gyp verb extracted file from tarball include/node/node_api.h
gyp verb extracted file from tarball include/node/node_api_types.h
gyp verb extracted file from tarball include/node/node_buffer.h
gyp verb extracted file from tarball include/node/node_object_wrap.h
gyp verb extracted file from tarball include/node/node_version.h
gyp verb extracted file from tarball include/node/uv.h
gyp verb extracted file from tarball include/node/v8-inspector-protocol.h
gyp verb extracted file from tarball include/node/v8-inspector.h
gyp verb extracted file from tarball include/node/v8-platform.h
gyp verb extracted file from tarball include/node/v8-profiler.h
gyp verb extracted file from tarball include/node/v8-testing.h
gyp verb extracted file from tarball include/node/v8-util.h
gyp verb extracted file from tarball include/node/v8-value-serializer-version.h
gyp verb extracted file from tarball include/node/v8-version-string.h
gyp verb extracted file from tarball include/node/v8-version.h
gyp verb extracted file from tarball include/node/v8.h
gyp verb extracted file from tarball include/node/v8config.h
gyp verb extracted file from tarball include/node/zconf.h
gyp verb extracted file from tarball include/node/zlib.h
gyp verb extracted file from tarball include/node/uv/aix.h
gyp verb extracted file from tarball include/node/uv/android-ifaddrs.h
gyp verb extracted file from tarball include/node/uv/bsd.h
gyp verb extracted file from tarball include/node/uv/darwin.h
gyp verb extracted file from tarball include/node/uv/errno.h
gyp verb extracted file from tarball include/node/uv/linux.h
gyp verb extracted file from tarball include/node/uv/os390.h
gyp verb extracted file from tarball include/node/uv/posix.h
gyp verb extracted file from tarball include/node/uv/stdint-msvc2008.h
gyp verb extracted file from tarball include/node/uv/sunos.h
gyp verb extracted file from tarball include/node/uv/threadpool.h
gyp verb extracted file from tarball include/node/uv/tree.h
gyp verb extracted file from tarball include/node/uv/unix.h
gyp verb extracted file from tarball include/node/uv/version.h
gyp verb extracted file from tarball include/node/uv/win.h
gyp verb extracted file from tarball include/node/openssl/aes.h
gyp verb extracted file from tarball include/node/openssl/asn1.h
gyp verb extracted file from tarball include/node/openssl/asn1_mac.h
gyp verb extracted file from tarball include/node/openssl/asn1t.h
gyp verb extracted file from tarball include/node/openssl/async.h
gyp verb extracted file from tarball include/node/openssl/bio.h
gyp verb extracted file from tarball include/node/openssl/blowfish.h
gyp verb extracted file from tarball include/node/openssl/bn.h
gyp verb extracted file from tarball include/node/openssl/bn_conf.h
gyp verb extracted file from tarball include/node/openssl/bn_conf_asm.h
gyp verb extracted file from tarball include/node/openssl/bn_conf_no-asm.h
gyp verb extracted file from tarball include/node/openssl/buffer.h
gyp verb extracted file from tarball include/node/openssl/camellia.h
gyp verb extracted file from tarball include/node/openssl/cast.h
gyp verb extracted file from tarball include/node/openssl/cmac.h
gyp verb extracted file from tarball include/node/openssl/cms.h
gyp verb extracted file from tarball include/node/openssl/comp.h
gyp verb extracted file from tarball include/node/openssl/conf.h
... [logs removed]
gyp verb get node dir target node version installed: 10.13.0
gyp verb build dir attempting to create "build" dir: /home/auser/versions/app/node_modules/node-rdkafka/build
gyp verb build dir "build" dir needed to be created? /home/auser/versions/app/node_modules/node-rdkafka/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/auser/versions/app/node_modules/node-rdkafka/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/auser/versions/app/node_modules/node-rdkafka/config.gypi
gyp verb common.gypi checking for gypi file: /home/auser/versions/app/node_modules/node-rdkafka/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/auser/versions/app/node_modules/node-rdkafka/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/auser/.node-gyp/10.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/auser/.node-gyp/10.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/auser/versions/node-v10.13.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/auser/.node-gyp/10.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/auser/versions/app/node_modules/node-rdkafka',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/auser/.node-gyp/10.13.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/auser/versions/app/node_modules/node-rdkafka/build'
  LD_LIBRARY_PATH=/home/auser/versions/app/node_modules/node-rdkafka/build/Release/lib.host:/home/auser/versions/app/node_modules/node-rdkafka/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps; mkdir -p librdkafka; node ../util/configure
checking for OS or distribution... ok (ubuntu)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking executable libtool... failed (disable)
checking for pkgconfig (by command)... failed
checking for install (by command)...

```

**Comment by RicardoGralhoz** [comment]
I found a clue; when it hanged, I opened another terminal tab and found using `ps -x` that there is a `/home/auser/app/utils/install` process running, which belongs to my app and is probably being wrongfully called by the `./configure` process.

**Comment by RicardoGralhoz** [comment]
Confirming here this caused the installation or update to hang. After removing the `/home/auser/app/utils` from the `PATH` the installation continued past the previous point. It now failed due to a different reason (see below), so I'll close #825 and maybe I'll open a new one later.

---
```
../src/binding.cc:81:34: error: ‘GetCurrentEnvironment’ is not a member of ‘node’
   node::Environment* env = node::GetCurrentEnvironment(context);
                                  ^~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:81:34: note: suggested alternative: ‘CreateEnvironment’
   node::Environment* env = node::GetCurrentEnvironment(context);
                                  ^~~~~~~~~~~~~~~~~~~~~
                                  CreateEnvironment
```
