### ISSUE TITLE
Broker Transport Failure in SSL environment.

### ISSUE THREAD

**Issue by Arkh1** [Blizzard/node-rdkafka#826]
> Local: Broker transport failure\n    at Function.createLibrdkafkaError [as create] (/opt/app/webapps/ROOT/node_modules/node-rdkafka/lib/error.js:411:10)\n    at /opt/app/webapps/ROOT/node_modules/node-rdkafka/lib/client.js:350:28

> [2020-07-29 14:17:52,630] INFO [SocketServer brokerId=0] Failed authentication with /127.0.0.1 (SSL handshake failed) (org.apache.kafka.common.network.Selector)

We are transitioning from the kafka-node library to node-rdkafka.  Unfortunately we are getting a broker transport failure in our ssl environment when using node-rdkafka that we didn't experience with kafka-node.  That said, the non-ssl environments are working as expected.  

Any assistance would be greatly appreciated.

**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: MacOS Catalina
 - Node Version [e.g. 8.2.1]: 12.14.1
 - NPM Version [e.g. 5.4.2]: 6.13.4
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: 
 - node-rdkafka version [e.g. 2.3.3]: 2.9.0

**Steps to Reproduce**
Start server and attempt produce messages.

**node-rdkafka Configuration Settings**
``` javascript
'client.id': 'clientId',
'metadata.broker.list': 'brokerList',
'request.timeout.ms': 3000,
'message.send.max.retries': 3,
'debug': 'all'
'security.protocol': 'ssl',
'ssl.cipher.suites': 'TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256',
'ssl.keystore.location': '/path/to/keystore.p12',
'ssl.keystore.password': 'keystorePassword'
```

**Additional context**
Jenkins pipeline commands added specifically for node-rdkafka:
```
sh 'sudo yum -y groupinstall "Development Tools"'
sh 'sudo yum -y install openssl-devel'
sh 'openssl version'
sh 'export CPPFLAGS=-I/usr/include/openssl'
sh 'export LDFLAGS=-L/usr/lib64/openssl'
```

**Comment by Arkh1** [comment]
Alternatively is it possible for node-rdkafka to accept 
```
pfx: [
    {
        buf: fs.readFileSync('/path/to/file.jks'),
        passphrase: 'password123'
    }
]
```
as per `tls.connect` options in Node?
https://nodejs.org/docs/latest-v12.x/api/tls.html#tls_tls_ssl

**Comment by Arkh1** [comment]
After getting our build environment, runtime environment & Node openssl versions on 1.1.1 we were able to get it to work.
