### ISSUE TITLE
Unable to install node-rdkafka on MacOS BigSur

### ISSUE THREAD

**Issue by vikashvverma** [Blizzard/node-rdkafka#854]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]:  MacOS BigSur
 - Node Version [e.g. 8.2.1]: v12.15.0
 - NPM Version [e.g. 5.4.2]: 6.13.4
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++
 - node-rdkafka version [e.g. 2.3.3]: latest

**Steps to Reproduce**
npm i node-rdkafka
**node-rdkafka Configuration Settings**

**Additional context**
I get the following logs on running `npm i node-rdkafka`

```

> node-rdkafka@2.9.1 install /Users/vikash/node_modules/node-rdkafka
> node-gyp rebuild

/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: line 5: /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js: No such file or directory
npm WARN enoent ENOENT: no such file or directory, open '/Users/vikash/package.json'
npm WARN vikash No description
npm WARN vikash No repository field.
npm WARN vikash No README data
npm WARN vikash No license field.

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! node-rdkafka@2.9.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the node-rdkafka@2.9.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vikash/.npm/_logs/2020-12-04T01_57_01_830Z-debug.log
```

Additional logs from the log file:

```
376 warn enoent ENOENT: no such file or directory, open '/Users/vikash/package.json'
377 verbose enoent This is related to npm not being able to find a file.
378 warn vikash No description
379 warn vikash No repository field.
380 warn vikash No README data
381 warn vikash No license field.
382 verbose stack Error: node-rdkafka@2.9.1 install: `node-gyp rebuild`
382 verbose stack spawn ENOENT
382 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
382 verbose stack     at ChildProcess.emit (events.js:223:5)
382 verbose stack     at maybeClose (internal/child_process.js:1021:16)
382 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
383 verbose pkgid node-rdkafka@2.9.1
384 verbose cwd /Users/vikash/foo
385 verbose Darwin 20.1.0
386 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "node-rdkafka"
387 verbose node v12.15.0
388 verbose npm  v6.13.4
389 error code ELIFECYCLE
390 error syscall spawn
391 error file sh
392 error errno ENOENT
393 error node-rdkafka@2.9.1 install: `node-gyp rebuild`
393 error spawn ENOENT
394 error Failed at the node-rdkafka@2.9.1 install script.
394 error This is probably not a problem with npm. There is likely additional logging output above.
395 verbose exit [ 1, true ]
```

**Comment by fabianschmitthenner** [comment]
I usually have to reinstall the Xcode Command Line Tools after updating MacOS (also for after minor version updated). Some troubleshooting guide is here: https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md.

What usually works for me is the following, which first removes the broken xcode command line tools and then installs them freshly again:

```
sudo rm -rf $(xcode-select -print-path)
xcode-select --install
```

**Comment by zzswang** [comment]
How could I reinstall xcode-select?  I lot of softwares are broken now.

**Comment by fabianschmitthenner** [comment]
Oh no :( . Have you checked out https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md#solutions ? There is also the manual download option. 🤔

**Comment by zzswang** [comment]
Thank you, I'll have a try.

**Comment by zzswang** [comment]
Yes, follow [this spec](https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md#i-did-all-that-and-the-acid-test-still-does-not-pass--) fixed it.

**Comment by fabianschmitthenner** [comment]
cool 😊
