### ISSUE TITLE
No provider for SASL mechanism GSSAPI error

### ISSUE THREAD

**Issue by sathyarajagopal** [Blizzard/node-rdkafka#880]
Hello, I have written a Kafka producer app in NodeJS (which is deployed in a docker container) and using it I am trying to connect to the kerberized Kafka cluster in my organization using "node-rdkafka": "^2.10.1". It was working fine till yesterday. However beginning today I am facing the below error:

_Error: No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN\n    at Function.createLibrdkafkaError [as create] (/usr/local/src/www/node_modules/node-rdkafka/lib/error.js:423:10)\n    at /usr/local/src/www/node_modules/node-rdkafka/lib/client.js:196:28 +1ms 8ee6a387e6d9 22_

My app docker uses RHEL base image and has the RHEL dev tools installed as well.
yum --setopt=group_package_types=mandatory,default,optional groupinstall -y "Development Tools"

Can someone help me to get through this issue?

**Comment by sathyarajagopal** [comment]
Please find my docker file below:

FROM rhel7:base
RUN curl -o node-v12.16.1-linux-x64.tar.xz http://abc/node-v12.16.1-linux-x64.tar.xz/12.16.1/node-v12.16.1-linux-x64.tar.xz-12.16.1.xz; \
  tar -xf node-v12.16.1-linux-x64.tar.xz --directory /usr/local --strip-components 1; \
  rm -f node-v12.16.1-linux-x64.tar.xz
RUN npm install -g npmrc
RUN yum -y install krb5-workstation krb5-libs
RUN yum -y install openldap-clients
RUN yum group mark-install "Development Tools"
RUN yum group mark-convert "Development Tools"
RUN yum --setopt=group_package_types=mandatory,default,optional groupinstall -y "Development Tools"
RUN yum group list

**Comment by sathyarajagopal** [comment]
Closing this as it is no more an issue.
