### ISSUE TITLE
How to use topic patterns for consumer?

### ISSUE THREAD

**Issue by stealthrabbi** [Blizzard/node-rdkafka#901]
I'm using the consumer stream API, and I can subscribe to singel topics. But, I'm not sure how to subscribe to a topic. When I attempt to do so, I get an error:

```

    const consumerConfig: ConsumerGlobalConfig = {
      "metadata.broker.list": myServerVar,
      "group.id": myGroupId,
      "enable.auto.commit": false,
      "allow.auto.create.topics": true,
    };
    const topicConfig: ConsumerTopicConfig = {
      "auto.offset.reset": "latest",
      "consume.callback.max.messages": 100,
    };

    const consumerStream = KafkaConsumer.createReadStream(
      consumerConfig,
      topicConfig,
      {
        topics: ["MyProj.*.SOMEVAL.1"],
      }
    );
```

I've also tried creating a `RegExp` and providing that to the `topics` property, but I get the same error

```
    const regex = new RegExp("MyProj.*.SOMEVAL.1");
    const consumerStream = KafkaConsumer.createReadStream(
      consumerConfig,
      topicConfig,
      {
        topics: [regex],
      }
    );
 ```

```
events.js:353
      throw er; // Unhandled 'error' event
      ^
LibrdKafkaError: Broker: Unknown topic or partition
    at Function.createLibrdkafkaError [as create] (\myproj\\node_modules\node-rdkafka\lib\error.js:423:10)
    at \myproj\\node_modules\node-rdkafka\lib\kafka-consumer.js:468:29
Emitted 'error' event on KafkaConsumerStream instance at:
    at onread (\myproj\\node_modules\node-rdkafka\lib\kafka-consumer-stream.js:187:12)
    at \myproj\\node_modules\node-rdkafka\lib\kafka-consumer.js:470:9 {
  code: 3,
  errno: 3,
  origin: 'local'
}

```

**Comment by cvhooser** [comment]
I'm not using the readStream api, but in the standard api this works: `[/^ MyProj\..*\..*\.1/]`
