### ISSUE TITLE
Unable to install node-rdkafka: Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by nimrod-codota** [Blizzard/node-rdkafka#911]
**Environment Information**
 - OS: Mac
 - Node Version: 14.17.5
 - NPM Version: 7.21.1
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version: 2.11.0

**Steps to Reproduce**

`npm -i node-rdkafka`

I've reinstalled npm, node-gyp, command line tools, and kafka - all of which for several times - to no avail.
Here's the npm output:

```
npm ERR! code 6
npm ERR! path /Users/nimast/dev/repos/codota-ide-support/node_modules/node-rdkafka
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.17.5 | darwin | x64
npm ERR! gyp info find Python using Python version 3.8.2 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/nimast/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/nimast/dev/repos/codota-ide-support/node_modules/node-rdkafka/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/nimast/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/nimast/Library/Caches/node-gyp/14.17.5/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/nimast/Library/Caches/node-gyp/14.17.5',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/nimast/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/nimast/Library/Caches/node-gyp/14.17.5/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/nimast/dev/repos/codota-ide-support/node_modules/node-rdkafka',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! (node:20050) UnhandledPromiseRejectionWarning: Error: spawn Unknown system error -86
npm ERR!     at ChildProcess.spawn (internal/child_process.js:403:11)
npm ERR!     at spawn (child_process.js:667:9)
npm ERR!     at Object.spawnWithSignal [as spawn] (child_process.js:871:17)
npm ERR!     at Gyp.spawn (/Users/nimast/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:173:25)
npm ERR!     at doBuild (/Users/nimast/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:188:20)
npm ERR!     at /Users/nimast/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:117:7
npm ERR!     at /Users/nimast/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/which/which.js:84:35
npm ERR! (Use `node --trace-warnings ...` to show where the warning was created)
npm ERR! (node:20050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! (node:20050) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! gyp ERR! Completion callback never invoked!
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/Users/nimast/.nvm/versions/node/v14.17.5/bin/node" "/Users/nimast/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/nimast/dev/repos/codota-ide-support/node_modules/node-rdkafka
npm ERR! gyp ERR! node -v v14.17.5
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! Node-gyp failed to build your package.
npm ERR! gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nimast/.npm/_logs/2021-08-30T16_14_01_545Z-debug.log
```

**node-rdkafka Configuration Settings**

**Additional context**

Also tried other node / node-gyp combinations such as node 14.16.1 and node-gyp 8.2.0, to no avail

**Comment by samhwang** [comment]
I'm encountering these issues as well. Tried other node / node-gyp combinations too.

OS: Mac
Node Version: 14.18.1
NPM Version: 6.14.15
C++ Toolchain [e.g. Visual Studio, llvm, g++]:
node-rdkafka version: latest
