### ISSUE TITLE
kafka error when starting server  |  symbol not found reference error macOS BigSur

### ISSUE THREAD

**Issue by codeByAshu01** [Blizzard/node-rdkafka#919]
**Environment Information**
 - OS [ Mac, 11.2.3 (20D91), M1 chipset]: 
 - Node Version [e.g. v16.8.0]:
 - NPM Version [e.g. 7.21.0]:

 - node-rdkafka version [latest default]:

**Steps to Reproduce**
npm install 
then npm start
**node-rdkafka Configuration Settings**

├── @babel/polyfill@7.12.1
├── @hapi/joi-date@2.0.1
├── app-root-path@3.0.0
├── async@3.2.2
├── cors@2.8.5
├── crypto-js@4.1.1
├── dotenv@10.0.0
├── eslint-config-airbnb-base@14.2.1
├── eslint-config-node@4.1.0
├── eslint-config-prettier@8.3.0
├── eslint-plugin-import@2.25.2
├── eslint-plugin-node@11.1.0
├── eslint-plugin-prettier@4.0.0
├── eslint@7.32.0
├── express@4.17.1
├── joi@17.4.2
├── knex@0.95.12
├── lodash@4.17.21
├── moment@2.29.1
├── mongoose@6.0.12
├── monk@7.3.4
├── mysql@2.18.1
├── node-kafka-partitioner@1.0.3
├── node-path@0.0.3
├── node-rdkafka@2.11.0
├── nodemon@2.0.14
├── postman-request@2.88.1-postman.30
├── prettier@2.4.1
├── redis@3.1.2
├── uniqid@5.4.0
├── winston-daily-rotate-file@4.5.5
├── winston-logrotate@1.3.0
└── winston@3.3.3
**Additional context**
Debugger listening on ws://127.0.0.1:9229/9f18ac26-fe5b-433d-88fb-b9439ea1ec38
For help, see: https://nodejs.org/en/docs/inspector
2021-10-28 23:48:03.146 info: Load local configuration from/Users/Licious/Desktop/workspace/cart-service/config/development.json
2021-10-28 23:48:03.342 error: Error: dlopen(/Users/Licious/Desktop/workspace/cart-service/node_modules/node-rdkafka/build/Release/node-librdkafka.node, 1): Symbol not found: __ZN7RdKafka5Topic10OFFSET_ENDE
  Referenced from: /Users/Licious/Desktop/workspace/cart-service/node_modules/node-rdkafka/build/Release/node-librdkafka.node
  Expected in: flat namespace
 in /Users/Licious/Desktop/workspace/cart-service/node_modules/node-rdkafka/build/Release/node-librdkafka.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at bindings (/Users/Licious/Desktop/workspace/cart-service/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/Licious/Desktop/workspace/cart-service/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/Licious/Desktop/workspace/cart-service/node_modules/node-rdkafka/lib/client.js:14:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by cannguyen-ai** [comment]
I'm facing the same issue.

**Comment by RandomRaine** [comment]
^^ same issue here. @_@

**Comment by mustafahasankhan** [comment]
Same for me @_@

**Comment by sanketdhoble** [comment]
Same issue for us, in node v18 as well.

**Comment by kapekost** [comment]
+1
