### ISSUE TITLE
npm install node-rdkafka - failing on my mac

### ISSUE THREAD

**Issue by rohansai7** [Blizzard/node-rdkafka#951]
I am getting the following errors when I run `npm install node-rdkafka`

rohansai@Rohans-MacBook-Pro scc-notifications-filter % npm install node-rdkafka

> node-rdkafka@2.9.1 install /Users/rohansai/Desktop/Security Insights/PSIRTS/scc-notifications-filter/node_modules/@security-services/kafka-consumer/node_modules/node-rdkafka
> node-gyp rebuild

  ACTION deps_librdkafka_gyp_librdkafka_target_configure deps/librdkafka/config.h
/bin/sh: Insights/PSIRTS/scc-notifications-filter/node_modules/@security-services/kafka-consumer/node_modules/node-rdkafka/build/Release/lib.host:/Users/rohansai/Desktop/Security: No such file or directory
mklove/modules/configure.base: line 957: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 957: $MKL_OUTDBG: ambiguous redirect
downloading missing module builtin from http://github.com/edenhill/mklove/raw/master/modules/configure.builtin
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download builtin:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module builtin not found (required by base)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
downloading missing module host from http://github.com/edenhill/mklove/raw/master/modules/configure.host
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download host:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module host not found (required by base)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
downloading missing module cc from http://github.com/edenhill/mklove/raw/master/modules/configure.cc
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download cc:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module cc not found (required by base)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 957: $MKL_OUTDBG: ambiguous redirect
downloading missing module cxx from http://github.com/edenhill/mklove/raw/master/modules/configure.cxx
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download cxx:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module cxx not found (required by self)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
downloading missing module lib from http://github.com/edenhill/mklove/raw/master/modules/configure.lib
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download lib:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module lib not found (required by self)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
downloading missing module pic from http://github.com/edenhill/mklove/raw/master/modules/configure.pic
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download pic:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module pic not found (required by self)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
downloading missing module atomics from http://github.com/edenhill/mklove/raw/master/modules/configure.atomics
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download atomics:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module atomics not found (required by self)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
downloading missing module good_cflags from http://github.com/edenhill/mklove/raw/master/modules/configure.good_cflags
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download good_cflags:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module good_cflags not found (required by self)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
downloading missing module socket from http://github.com/edenhill/mklove/raw/master/modules/configure.socket
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download socket:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module socket not found (required by self)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
downloading missing module zlib from http://github.com/edenhill/mklove/raw/master/modules/configure.zlib
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download zlib:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module zlib not found (required by self)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
downloading missing module libzstd from http://github.com/edenhill/mklove/raw/master/modules/configure.libzstd
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download libzstd:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module libzstd not found (required by self)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
downloading missing module libssl from http://github.com/edenhill/mklove/raw/master/modules/configure.libssl
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download libssl:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module libssl not found (required by self)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
downloading missing module libsasl2 from http://github.com/edenhill/mklove/raw/master/modules/configure.libsasl2
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download libsasl2:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module libsasl2 not found (required by self)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
downloading missing module parseversion from http://github.com/edenhill/mklove/raw/master/modules/configure.parseversion
mklove/modules/configure.base: line 983: $MKL_OUTDBG: ambiguous redirect
Failed to download parseversion:
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
mklove/modules/configure.base: line 1966: wget: command not found
mklove/modules/configure.base: line 974: $MKL_OUTDBG: ambiguous redirect
Module parseversion not found (required by self)
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
Unknown option prefix=/Users/rohansai/Desktop/Security Insights/PSIRTS/scc-notifications-filter/node_modules/@security-services/kafka-consumer/node_modules/node-rdkafka/build/deps
mklove/modules/configure.base: line 966: $MKL_OUTDBG: ambiguous redirect
Usage: ./configure [OPTIONS...]

 mklove configure script - mklove, not autoconf
 Copyright (c) 2014-2019 Magnus Edenhill - https://github.com/edenhill/mklove

 librdkafka - The Apache Kafka C/C++ library
 Copyright (c) 2012-2019 Magnus Edenhill

Development options:
   --enable-devel                       Enable development asserts, checks, etc [n]
   --disable-devel                      Disable development asserts, checks, etc
   --enable-valgrind                    Enable in-code valgrind suppressions [n]
   --disable-valgrind                   Disable in-code valgrind suppressions
   --enable-refcnt-debug                Enable refcnt debugging [n]
   --disable-refcnt-debug               Disable refcnt debugging
   --enable-sharedptr-debug             Enable sharedptr debugging [n]
   --disable-sharedptr-debug            Disable sharedptr debugging

Feature options:
   --enable-lz4-ext                     Enable external LZ4 library support (builtin version 1.9.2) [y]
   --disable-lz4-ext                    Disable external LZ4 library support (builtin version 1.9.2)
   --enable-lz4                         Deprecated: alias for --enable-lz4-ext [y]
   --disable-lz4                        Deprecated: alias for --enable-lz4-ext
   --enable-c11threads                  Enable detection of C11 threads support in libc [y]
   --disable-c11threads                 Disable detection of C11 threads support in libc
   --enable-syslog                      Enable logging to syslog [y]
   --disable-syslog                     Disable logging to syslog

Honoured environment variables:
  CC, CPP, CXX, CFLAGS, CPPFLAGS, CXXFLAGS, LDFLAGS, LIBS,
  LD, NM, OBJDUMP, STRIP, PKG_CONFIG, PKG_CONFIG_PATH,
  STATIC_LIB_<libname>=.../libname.a

make: *** No rule to make target `../deps/librdkafka/config.h', needed by `11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node@12/12.22.12/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/usr/local/Cellar/node@12/12.22.12/bin/node" "/usr/local/Cellar/node@12/12.22.12/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rohansai/Desktop/Security Insights/PSIRTS/scc-notifications-filter/node_modules/@security-services/kafka-consumer/node_modules/node-rdkafka
gyp ERR! node -v v12.22.12
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN scc-notifications-filter@0.0.1 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.9.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.9.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rohansai/.npm/_logs/2022-04-29T12_15_27_747Z-debug.log

**Comment by 15096819** [comment]
This error seems mean the "librdkafka" build failed, thus the head file is missing for further node binding build.
I got the same error when my default "make" was version 3.8 and "gcc" was 4.8.2
I succeed the build by change the "make" to version 4.2 and "gcc" to 4.9.2 in my environment.

**Comment by Tete1805** [comment]
If it helps, I also had to install build-essential on my fresh wsl2 Ubuntu 22.04 install (`sudo apt-get install build-essential`).
I also tried installing gcc (`sudo apt-get install gcc`) first but I'm not sure if it was required.
